### ISSUE TITLE
Access restrictions

### ISSUE THREAD

**Issue by AdyRock** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#1]
Hi,

Now that the API is local, are there any access limits on the API?
For example, can I poll the events every 2 seconds?

**Comment by vhenriet-sfy** [comment]
Hi,

There is no rate limit on API endpoints. But be aware that calling them too frequently will impact your gateway performance and you might observe latency during product control.

You can safely fetch events every 2s without any issue.
