### ISSUE TITLE
How to get support when current TaHoma Box / POD is not showing up in MyAccount

### ISSUE THREAD

**Issue by jensihnow** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#10]
Hi,

I'm facing an interesting issue when trying to enable Developer Mode. I'm using TaHoma >10 years and at some point had to switch the box due to retirement of the old boxes. I made a successful transition, but somehow on the Somfy MyAccount it continues to list the old box and not the one I'm currently using. 

The old Box listed starts with 0201-xxxx-xxxx, whereas the one I'm using is 1202-xxxx-xxxx. Of course the I can't enable anything for the later as it is not listed and the 0201-.. box is shown as "inactive". 

A while ago I tried sending an email to Somfy, but never received an answer or solution to this problem. I've been waiting for a local API since being one of the first customers for TaHoma in Germany. Now it becomes available and I can't using it, any help appreciated. I understand this question is not related to the Code or API directly, please let me know what the best approach would be.

Thanks a lot,
Jens

**Comment by llavorel-somfy** [comment]
Hi Jens,
We have been able to complete the gateway transition. For a reason we could not explain, it was still PENDING.
You should find the correct gateway in the MyAccount section now !
