### ISSUE TITLE
For how long duration is the JsessionID and Token valid?

### ISSUE THREAD

**Issue by larhedse** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#101]
So I have somewhat of a problem with authorization, and the question I seem to stumble upon is for how long time the Token, and for that matter the JsessionID is valid? Is it 10 minutes for both, or what time limitations are there?

**Comment by bjorn085** [comment]
According to : https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/85
token should never expire.

**Comment by larhedse** [comment]
Large thanks!

My issue seems to be to activate the Token - which never seems to work for me. Most likely I am doing something wrong here, so I need to test and well "run into the wall a few hundred times" to get the syntax correct.  What I currently get is "{ "errorCode": "RESOURCE_ACCESS_DENIED",  "error": "Bad credentials" }" - very funny...

**Comment by larhedse** [comment]
On no, I give up this. I can not activate any token at all - I have to different errors:

If I send:

curl -X POST https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxx-2502-6214/local/tokens -H "Content-Type:application/json" -H "Authorization: Bearer xxxxb35886ccd99add9f" -d '{"label":"xxxx token","token":"xxxxb35886ccd99add9f","scope":"devmode"}'

The response is: Bad credentials

If I send:

curl -X POST https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxx-2502-6214/local/tokens -H "Content-Type:application/json" -b "JSESSIONID=xxxx3E41DED396E94FC755707DB53498" -d '{"label":"xxxx token","token":"xxxxb35886ccd99add9f","scope":"devmode"}'

The response is: Invalid JSON

I do not understand why someone has decided to make this so impossible, at least that is how my current view is. First session id, then token, then activate that token (why was not this done in the previous step?) - why sessionId when the thing needed is the token - it could all be generated at the first call, three calls makes me wonder why?

**Comment by bjorn085** [comment]
Authorization Bearer is for local calls to gateway-xxx.local. So your first request is not right. 
Everything that is after "Security"[ point of the doc](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode#security) concerns the local calls to tahoma box. For all calls to central server you should only use what is described before. 

So I suppose you successfully get a token from "Generate a token" method and you have to activate it, the doc is : 

<html>
<body>
<h3 tabindex="-1" dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Activate your token</h3><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Use your personal label to identify your tokens.</p><h4 tabindex="-1" dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-method-post-1" class="anchor" aria-hidden="true" href="https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode#method-post-1" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg></a>Method: POST</h4><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px 1em; color: var(--color-fg-muted); border-left: 0.25em solid var(--color-border-default); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="snippet-clipboard-content notranslate position-relative overflow-auto" style="box-sizing: border-box; position: relative !important; overflow: auto !important; margin-top: 0px; margin-bottom: 0px;"><pre class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; margin-top: 0px; margin-bottom: 16px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; color: var(--color-fg-default); background-color: var(--color-canvas-subtle); border-radius: 6px;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0px; margin: 0px; white-space: pre; background: transparent; border-radius: 6px; word-break: normal; border: 0px; display: inline; overflow: visible; line-height: inherit; overflow-wrap: normal;">https://{{url}}/enduser-mobile-web/enduserAPI/config/{{pod}}/local/tokens
</code></pre></div></blockquote><h4 tabindex="-1" dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-headers-2" class="anchor" aria-hidden="true" href="https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode#headers-2" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg></a>Headers</h4>

Key | Value
-- | --
Content-Type | application/json
Cookie | JSESSIONID=THE_VALUE_YOU_GOT_FROM_THE_LOGIN

<h4 tabindex="-1" dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-body-raw" class="anchor" aria-hidden="true" href="https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode#body-raw" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg></a>Body (<strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">raw</strong>)</h4><div class="highlight highlight-source-json notranslate position-relative overflow-auto" dir="auto" style="box-sizing: border-box; position: relative !important; overflow: auto !important; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; margin-top: 0px; margin-bottom: 0px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; color: var(--color-fg-default); background-color: var(--color-canvas-subtle); border-radius: 6px; word-break: normal;">{
  <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"label"</span>: <span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>Toto token<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
  <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"token"</span>: <span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>{{token}}<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
  <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"scope"</span>: <span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>devmode<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>
}</pre></div>
</body>
</html>


I don't know well cURL but here is how POSTMAN translate my request (that I cannon retest currently but which was working short time before). 


curl --location 'https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/mypin/local/tokens' \
--header 'Content: application/json' \
--header 'Cookie: JSESSIONID=ABCDEF' \
--header 'Content-Type: application/json' \
--data '{
  "label": "token blabla",
  "token": "123456",
  "scope": "devmode"
}'


So your second request seems to me not far from the right one... maybe you don't use correctly "-b" option ? Don't know how to use it.

**Comment by larhedse** [comment]
Thanks for all your help!

I kind of tried the last one, with a few minor alterations (singel vs double quotes...):

{"errorCode":"INVALID_API_CALL","error":"Invalid JSON format or type in request body"}

I just do not understand why there are three calls for returning an active token - it should be much easier that this.

**Comment by larhedse** [comment]
Okay, so what I seem to have stumbled onto is a Windows thing. One has to use escape character <\>, like this in the body part:

-d "{\"label\":\"xxxx token\",\"token\":\"xxxxf6d39555004b57e9\",\"scope\":\"devmode\"}"

Or in full, for windows then:

curl https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxx-2502-6214/local/tokens -H "Content: application/json" -b "JSESSIONID=xxxx128847A462E3394A3CDA52DA2A7A" -H "Content-Type:application/json" -d "{\"label\":\"xxxx token\",\"token\":\"xxxxf6d39555004b57e9\",\"scope\":\"devmode\"}"

I still would prefer though to get ONE call that makes everything IN ONE GO - there is just no reason for three calls: Get sessionID, Get Token, Activate Token. Just do all that on the cloud side, and give me my active token direct....!

**Comment by bjorn085** [comment]
I can agree on the generate/activate token, I don't see either any interest to have separate calls as token cannot be deactivated, and custom name could be passed to generate token API.

However, having to distinct APIs for authenticate and token generation is logical : the "authenticate" method is ... here to authenticate on distant server, and then you can do several different calls and things (generate, delete, list active tokens). As authenticate API ask the clear password of user account, it seems to me a good practice that you don't have to give it at each time when you want to manage your tokens, but only one time to get a temporary credential (JsessionId) that you can use on several calls. 
And has you have to authenticate on two different devices (on overkiz to manage token, and on local box with token), is it also logical to have two different authentication methods. 

So, maybe (?) it would be possible to have two calls rather than 3, but not only one, this would not be a good design.
