### ISSUE TITLE
ExecutionRegisteredEvent not available via local API

### ISSUE THREAD

**Issue by iMicknl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#102]
Is there a list of all events that are present when you use the Somfy TaHoma Developer Mode? 

When I execute a command (like `"off"`) on the `io:DimmableLightIOComponent`, I only get `DeviceStateChangedEvent`. I can reproduce this for cover devices as well.

Via the cloud API I get multiple events:
- `ExecutionRegisteredEvent`
- `ExecutionStateChangedEvent`
- `DeviceStateChangedEvent`
- `ExecutionStateChangedEvent`

Especially the execution registered and execution state changed are important to understand if a command has been executed.

Hub: Somfy TaHoma v2
Firmware: 2023.1.4-7

**Comment by bjorn085** [comment]
Hi,
on my side for shutter events (open/close/stop), when I send command to somfy shutter io modules or velux, I indeed get events of type : ExecutionRegisteredEvent, CommandExecutionStateChangeEvent on command failure, ExecutionStageCHangeEvent on command completed, and DeviceStateChangeEvent. 

So either : events sent depend on the component / command activated (but it seems to me strange that at least ExecutionRegisteredEvent is not thrown on every execution type), or maybe you miss some events ? Do you register the listener before calling /exec ?

**Comment by iMicknl** [comment]
Thanks @bjorn085, I will give it another try. Do you have the same hub and firmware?

**Comment by bjorn085** [comment]
This is a Tahoma v2 yes. For firmware version, is this available on mobile app ? Otherwise i'll check later on api directly. But I must be on latest version

**Comment by iMicknl** [comment]
Only via the website (or API).

**Comment by bjorn085** [comment]
@iMicknl  : 
"protocolVersion": "2023.1.4-9"

**Comment by iMicknl** [comment]
Seems to work now in 2023.1.4-12. Perhaps it is fixed, or it was just an issue on my side / my box.
