### ISSUE TITLE
Command pairOneWayController parameters

### ISSUE THREAD

**Issue by devsseb** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#104]
Hello,

Where is it possible to find the documentation for the command of the roller shutter pairing command "pairOneWayController" ?

I don't see what the "paramsSig" parameter refers to

`{
    "nparams":1,
    "commandName":"pairOneWayController",
    "paramsSig":"p1,*p2"
}`

Thanks

**Comment by llavorel-somfy** [comment]
Hi @devsseb 
What are you trying to achieve ?

**Comment by devsseb** [comment]
Hi,

I'm trying to pair a roller shutter with a Smoove Origin IO remote from the API.

**Comment by llavorel-somfy** [comment]
Hi @devsseb 

The API is not made for such use cases but only for controlling the devices.

If you want to pair a remote like Smoove Origin to your Shutter, please follow the instructions of the product or contact your installer.

**Comment by devsseb** [comment]
Thank you for your reply. I'm just going to use the classic method then.

Can you nevertheless tell me what the pairOneWayController command is used for?
