### ISSUE TITLE
Local API not available when Tahoma Switch is offline

### ISSUE THREAD

**Issue by BernoldNL** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#105]
It seems the Tahoma Switch with version 2023.1.4-12 can not be reached locally when it can not reach the cloud. Could it be that it's too busy reconnecting for local commands to get through? And can it be improved?

**Comment by iMicknl** [comment]
@BernoldNL how did you try this? I don't face any issues with my TaHoma V2 when I disable internet access. Haven't tried this on my TaHoma Switch yet.

**Comment by BernoldNL** [comment]
@iMicknl Well, today it's going offline and back online all day long. I'm getting timeouts on about 50% of my GET/POST commands. And every time that happens, the LED is red.
Locally it is definitely still connected to wifi, otherwise it would show up in my router's log.

**Comment by nickngsr** [comment]
I don't have any issues with offline Tahoma Switches, we even have one in an environment with no internet connection. As long as you save and reuse the offline token you generate you shouldn't have any issues.

**Comment by BernoldNL** [comment]
Thanks, but the token is not the issue. When ithe gateway goes back online I can GET and POST without any problem with the same token. Today it worked well, faster too. But it has to be reliable all the time.

**Comment by BernoldNL** [comment]
> Hi @BernoldNL
> 
> Still facing any issue here ?

I can check in the next few days by blocking it on my router and will get back to you after that.

Good to see you're checking issues again. Thanks for that.

**Comment by BernoldNL** [comment]
@llavorel-somfy I can't reproduce this issue anymore with version 2023.6.4-9 installed. So I will close this issue.
