### ISSUE TITLE
[Garage] Core:OpenClosedPartialState, Close state taking very long until correct

### ISSUE THREAD

**Issue by rwzdoorn** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#106]
Hi,

I have a Dexxo Smart IO and a Tahoma Switch with developer mode enabled. I can talk with the API via this documentation (https://www.zwaveforum.se/viewtopic.php?t=7130) . Currently, when I use a KeyGo IO to open my garage door the State changes correctly to the 'open' state.

`{"type":3,"name":"core:OpenClosedPartialState","value":"open"}`

When I close the door within a minute with the KeyGo IO the state stays on 'open' (but it's being closed). Even after one hour the state is still open.

What I would expect:
`{"type":3,"name":"core:OpenClosedPartialState","value":"closed"}`

Refreshing the state can take up at least an hour which I would not expect. 

Please fix this..

**Comment by rwzdoorn** [comment]
Update on this matter: I've installed a Somfy Smove IO, this is giving the correct feedback if I close the garage it's being updated as 'closed'. It looks like the KeyGo IO only gives feedback when the door is opening but not closing.

**Comment by DuschdrBabbe** [comment]
I have the same issue: the status isn't transmitted when the gate is opened or closed using the remote control.

Would it work if I connect Overkiz via the cloud?

**Comment by llavorel-somfy** [comment]
Closing as it duplicates : https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/128

@DuschdrBabbe issue is related to the use of the KeyGo control to steer in local the gate. This is not an API problem
