### ISSUE TITLE
RESOURCE_ACCESS_DENIED even using a valid token

### ISSUE THREAD

**Issue by poggow** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#107]
Hello,

I activated the Developer Mode via the portal and then, using POSTMAN, logged in, created a token, activated it (I could see it via the Get available tokens command).

I can also retrieve the API version via a GET https://gateway-{{pod}}.local:{{port}}/enduser-mobile-web/1/enduserAPI/apiVersion.

However I soon as I try to do anything requiring the use of the token retrieved above, I get the following response : 

```
{
    "error": "Not authenticated.",
    "errorCode": "RESOURCE_ACCESS_DENIED"
}
``` 

Even trying a basisc function like Get the Gateway description

```
curl --location 'https://gateway-{{pod}}.local:{{port}}/enduser-mobile-web/1/enduserAPI/setup/gateways' \
--header 'Authorization: Bearer {{token}}'
``` 

Thanks in advance for your help!

**Comment by BernoldNL** [comment]
Is this your problem? https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/52#issuecomment-1228130846

**Comment by poggow** [comment]
> Is this your problem? [#52 (comment)](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/52#issuecomment-1228130846)

Hello, 

Indeed, that's the issue. I was using the uuid returned by the "Get available tokens" command.

Thank you for your help!!
