### ISSUE TITLE
Delete token doesn't work

### ISSUE THREAD

**Issue by marekburiak** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#115]
I generated and activated a token which I could then see using "Get available tokens".
I tried to generate and a activate another token (using a different label) but when I called "Get available tokens" I still saw just the one I created originally.
So then I tried to delete the existing token using uuid from "Get available tokens". The API returns a success but when I call  "Get available tokens" I can still see the original token there.

Get API version returns "protocolVersion": "2023.4.4-9" and I am using it with a CONNEXOON Window & Access device.

**Comment by bjorn085** [comment]
```
curl --location 'https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxxxx/local/tokens/devmode' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=xxxxx'
```

=> One token listed


> curl --location 'https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxxxx/local/tokens/generate' \
> --header 'Content-Type: application/json' \
> --header 'Cookie: JSESSIONID=xxxxx'; 

=> Answer ok, with token in body


```
curl --location 'https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxxx/local/tokens' \
--header 'Content: application/json' \
--header 'Cookie: JSESSIONID=xxxxx \
--header 'Content-Type: application/json' \
--data '{
  "label": "token test 15112023",
  "token": "token",
  "scope": "devmode"
}'
```

=> Answer 200 OK with request id

then, again list token  : 

I see my old token and the new one. I can get the new one uuid to use it in delete : 

```
curl --location --request DELETE 'https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxxxx/local/tokens/**uuid**' \
--header 'Content: application/json' \
--header 'Cookie: JSESSIONID=xxxx'
```
Answer ok, 
then new list token, and I've only one token left.


--- 
So : 
- you don't need to delete an existing token to get a new one, you can have more than one active token.
- If your call to list token doesn't show you a newly created token it's probably that it wasn't well created...
- Your delete request seems not working either... 

Your first problem seems to be generating and activating a new token, you should probably start by checking why it don't work.
