### ISSUE TITLE
KNX support

### ISSUE THREAD

**Issue by maumaumaumaumau** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#122]
Hi,
I use Somfys external blinds in combination with tahoma DIN Rail v1.1. 
In Somfys documentation it is stated that KNX support is possible with the din rail, for which specific case I've bought it. Unfortunately I cannot find the options stated in the documentation to assign.
Somfys phone support was also not very helpful in this regard and didn't contacted me to clarify about that topic.

Is there any way to assign the blinds from the ets export within the tahoma din rail as stated in the documentation? Is this possible with the developer mode or in any other way like downgrading the din rail? 

BR
mau

**Comment by llavorel-somfy** [comment]
Hi @maumaumaumaumau 
There is no link at all with the Developer Mode.
KNX can be setup with your TaHoma Din Rail using the ETS export through the TaHoma classic web app (a connection between your TaHoma Din Rail and your KNX network is needed).
