### ISSUE TITLE
Label and core:NameState get truncated to only 16 characters (io:DynamicRollerShutterIOComponent)

### ISSUE THREAD

**Issue by BernoldNL** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#124]
It seems under some circumstances that label get truncated to only 16 characters. I have seen this before for other devices, but it seems to be fixed for those somewhere in the past months. With io:DynamicRollerShutterIOComponent it still seems to happen.

Here are partial JSON:

On tahomalink.com

**"label": "12345678901234567890123456789012345678901234567890",**
"deviceURL": "io://xxxx-xxxx-xxxx/275166#1",

And:

**"label": "12345678901234567890123456789012345678901234567890",**
"deviceURL": "io://xxxx-xxxx-xxx/275166#2",

On Developer Mode:

"deviceURL": "io://xxxx-xxxx-xxxx/275166#1",
      ****"label": "1234567890123456",****

And:

 "deviceURL": "io://xxxx-xxxx-xxxx/275166#2",
      **"label": "12345678901234567890123456789012345678901234567890",**

Can the truncating be removed, so that label shows the same as in the app?

**Comment by llavorel-somfy** [comment]
Hi @BernoldNL 
We will not work on it
