### ISSUE TITLE
GetDevice request doesn't accept url encoded deviceURL

### ISSUE THREAD

**Issue by PetrJanura1** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#125]
From setup/devices request, I received deviceUrl io://{{pod}}/11111111

So I tried to fetch this device using API. My assumption was that standard URL encoding is going to work:

https://gateway-{{pod}}.local:8443/enduser-mobile-web/1/enduserAPI/setup/devices/io%3A%2F%2F{{pod}}%2F11111111

But I received this response:
{
   "error": "No such device : \"io%3A%2F%2F{{pod}}%2F11111111\"",
   "errorCode": "NO_SUCH_DEVICE"
}

Could you please specify in documentation which encoding am I supposed to use? URL encoding, base64 or ?

**Comment by BernoldNL** [comment]
It's correct. You can also see this in the curl example [here](https://somfy-developer.github.io/Somfy-TaHoma-Developer-Mode/#/Setup/get_setup_devices__deviceURL_).

But make sure you are using the **entire** deviceURL.

Examples:
- io://1234-5678-9012/11111111 becomes io%3A%2F%2F1234-5678-9012%2F11111111
- io//1234-5678-9012/11111111/1 becomes io%3A%2F%2F1234-5678-9012%2F11111111%2F1
- io//1234-5678-9012/11111111#1 becomes io%3A%2F%2F1234-5678-9012%2F11111111%231
- io//1234-5678-9012/11111111/1#1 becomes io%3A%2F%2F1234-5678-9012%2F11111111%2F1%231
