### ISSUE TITLE
[Lebanon] [Italy] Developer mode not available

### ISSUE THREAD

**Issue by makhlouta** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#126]
Hi,
I have a Tahoma V2 running the latest firmware, but I don't have developer mode in settings. Maybe because I am in a country that this is not activated yet? Because even clicking the contact support in the app sends me to a 404 error page.

I cannot find any contact for Somfy (local Somfy don't have any clue about this). Is there a way around it to activate the developer mode?

**Comment by llavorel-somfy** [comment]
Hi @makhlouta 

Where are you based ?

**Comment by makhlouta** [comment]
> Hi @makhlouta
> 
> Where are you based ?

Lebanon

**Comment by guillian77** [comment]
Hello,
Same on the "Connectivity Kit", the "developper mode" option do not apear any more after an update.
No possibilities to control rollers from Home Assistant or something similar.

**Comment by llavorel-somfy** [comment]
For information : https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/12

**Comment by makhlouta** [comment]
is somfy going to comment on this? are we getting local API access on tahoma v2 anytime soon?

**Comment by shASseven** [comment]
> Hello, Same on the "Connectivity Kit", the "developper mode" option do not apear any more after an update. No possibilities to control rollers from Home Assistant or something similar.

Hey,
 i’ve got the Same issue. After working very Fine the last months, i can‘t Control Rollers from HA since today. No Developer Mode Option anymore. Will there be a fix?

**Comment by llavorel-somfy** [comment]
Hi @shASseven 

This issue is about the initial activation of the developer mode from somfy.it or somfy.com.lb.

If you used if for the last months then I guess you haven't faced such issue as you were able to activate the mode. 

If you encounter another issue, please open another issue. If you face the same initial activation issue, please provide more details (gateway type, country, etc).

Thank you very much 🙏

**Comment by llavorel-somfy** [comment]
Hi @Agosh13 @makhlouta are you still facing the activation problem ?

**Comment by makhlouta** [comment]
I still don’t see an option to activate it

**Comment by drew-lanclos** [comment]
I'm having this issue in Canada. I've activated my TaHoma Beecon, but the Developer mode isn't available.

**Comment by llavorel-somfy** [comment]
Hi @drew-lanclos 

devMode is not available for TaHoma Beecon for the moment, see: https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/13

**Comment by llavorel-somfy** [comment]
I am closing this issue as devMode is now available in Italy and Lebanon
