### ISSUE TITLE
Error code 400

### ISSUE THREAD

**Issue by Stable-Adrian** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#129]
It seems since the 1024.1.4-11 update, a few users of my Homey app are reporting they are occasionally getting error code 400 when controlling their IO blinds via the cloud. The app has been in use for about 7 years now and this is the first time I have seen that error code come up.
It's strange the users that have reported this are still not using the local API, yet they say it started happening after their hub was updated.

**Comment by llavorel-somfy** [comment]
Hi @Stable-Adrian 
If it is not an issue with the local API, we cannot help
