### ISSUE TITLE
TaHoma North America is not compatible with Developer Mode

### ISSUE THREAD

**Issue by stormcrow2121** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#13]
Tahoma shows online but there is no button to Activate Developer Mode
![Screen Shot 2022-04-26 at 9 37 00 AM](https://user-images.githubusercontent.com/104445104/165325197-e927ce19-ca45-4516-819c-d18d46f364ee.png)
.

**Comment by llavorel-somfy** [comment]
Hi,
The current TaHoma version for North America is not compatible with the Developer Mode.

**Comment by atallo** [comment]
TaHoma version for Spain is compatible with the Developer Mode?

![image](https://user-images.githubusercontent.com/586093/165470640-77aecf22-f65a-422c-a0be-62f2307bad19.png)

**Comment by atallo** [comment]
Thank you. I thought he was a Tahoma (said "Tahoma está conectado/Tahoma is connected").

I think I made a really bad purchase. It's still under warranty but no longer supported :(

It would be nice to have a list that everyone can understand where it is indicated which products support this api, and which products will support it. And if there will be some kind of upgrade possible even if it is paying a percentage (or full pay).

**Comment by lonevvolf** [comment]
I have a Connectivity Kit, and I also don't see the Developer Mode option.

**Comment by austinginn** [comment]
Dev mode not supported for NA?  Do you have a timeline when this will be supported? At least give us some sort of local API instead...  This is a massive let down.

**Comment by aficustree** [comment]
@llavorel-somfy do you all have any idea of the blockers for NA support? I bought the system based on Somfy's website showing HomeKit support and local API access to only find out neither are actually supported in NA (which is completely non-obvious). Is there anything we can do to help develop the compatibility layer?
