### ISSUE TITLE
Unable to login to the UK site

### ISSUE THREAD

**Issue by mmg18** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#132]
I cannot login to the somfy.co.uk website to set a device in developer mode. The icon at the top (head icon) is gone.

If I go directly to https://www.somfy.co.uk/login the login seems successful, but I just get a blank page.

All the other Somfy websites (somfy.be, .de, .nl, .fr...) do work, but I need the uk website for a uk account...

**Comment by llavorel-somfy** [comment]
Hi @mmg18 
Are you still facing the issue ?

**Comment by mmg18** [comment]
> Hi @mmg18 Are you still facing the issue ?

No, I mailed the UK tech support and they fixed the website.

**Comment by llavorel-somfy** [comment]
Thank you for the feedback !
