### ISSUE TITLE
Local access stopped working after update

### ISSUE THREAD

**Issue by maumaumaumaumau** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#135]
Yesterday my Tahoma DIN Rail Gateway received an update (2024.2.4-13) and since then it's impossible to connect to it via local API.
I used the options GATEWAY-PIN.local:8443 and IP:8443 with my standard Somfy login credentials. I also tried to change / shorten and simplify my password, which also didn't work out.
Only Cloud API works for now with its usual limitations, but that is only a workaround.

![2024-06-21 23_48_31-Window](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/assets/89344616/f05b0b06-21cd-417c-8845-22d5fe8a6d4c)
![2024-06-21 23_48_03-Window](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/assets/89344616/d3866642-587e-496f-aeea-9415fd105206)

**Comment by BernoldNL** [comment]
What do you get when you try to open https://GATEWAY-PIN.local:8443/enduser-mobile-web/1/enduserAPI/apiVersion or https://IP:8443/enduser-mobile-web/1/enduserAPI/apiVersion in a browser?

**Comment by maumaumaumaumau** [comment]
Hi, I had a network issue with, which happened on the same time as the somfy box received the update.
Issue is resolved. Thank you for your support.
