### ISSUE TITLE
Probleme API - Utilisation Domotique Jeedom/VM Freebox Delta

### ISSUE THREAD

**Issue by mld-sebastien** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#141]
Actuellement, En suivi la doc les liens sont en 404 voir aussi en 401, Il y a un souci avec ces adresse ?? 
Pourriez-vous me dire la marche à suivre?

Cordialement.

**Comment by llavorel-somfy** [comment]
Bonjour @mld-sebastien 

Pouvez vous être plus précis sur les liens en question ?

**Comment by mld-sebastien** [comment]
Oui bien sur :

https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/login.

**Comment by llavorel-somfy** [comment]
Il n'y a pas de souci avec ces adresses, il faut bien suivre la doc et utiliser la bonne méthode de requete :

**Comment by mld-sebastien** [comment]
J'ai trouver pourquoi cela fonctionner pas. Il fallait le savoir il faut en aucun cas un mot de passe avec des caractérise spéciaux sinon cela fonctionne pas, un simple mot de passe somfy majuscule et chiffre fonctionne.
Merci
