### ISSUE TITLE
Once local api selected cannot revert to cloud api 

### ISSUE THREAD

**Issue by rudgej** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#146]
For some reason authentication expired on my 3 accounts. 

I was then given the option of cloud or local api. 

I chose local. I was then given instructions to login to somfy website and allow api access however this is not given as an option for my device (Connectivity kit ). 

The issue is that I am now unable to go back to the menu selecting api or cloud so am locked into api which I don't have. 

I have looked at the config options in the integration and there are no relevant options. 

As such my blinds no longer work. 

Please advise any work around to resolve this.

**Comment by AWahlqvist** [comment]
@rudgej: Same thing happened to me, I went to the integration page and deleted the hub and then readded it using the cloud option which solved it. For me, IDs of the entities changed though so that's something to be aware of.

I think this issue should perhaps be moved [here](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+overkiz%22).

**Comment by rudgej** [comment]
It is pretty poor if you are given an option which may well not work, that you then cannot back out of and the only solution is to delete the integration and start again which involves then editing multiple scripts and changing 15 wall panel settings. 

There must be a way to get back to the cloud integration surely. 

If not one click will cost me 2-3 hours work which is daft - epecially as no warning are given that the connection box is not supported ( which I have found out by trawling this site )

**Comment by AWahlqvist** [comment]
I agree, just wanted to share the only workaround I know.

For the record, my previous entity id’s from the integration were kind of random in nature, after readding the hub they now have IDs matching the device names. So for me, I think the next readd would be seamless (keeping the same IDs).

Still makes sense to update the UI though, but wanted to mention it if it helps someone.

**Comment by rudgej** [comment]
Thank you for this suggestion. 

I was very sceptical but it did actually work!

I am not sure where the " flag" is that sets this to local api. I looked in the config files but could not see anything. 

Thanks again 

Jeremy

**Comment by llavorel-somfy** [comment]
@rudgej if I am correct it is not linked to the TaHoma developer mode but it concerns the HA plugin you are using. If you have relocate your issue to the appropriate project, I will close this issue.

**Comment by iMicknl** [comment]
Home Assistant issues should be reported here; https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+overkiz%22. Please check first if there are any open issues.
