### ISSUE TITLE
First step does not work (anymore)...

### ISSUE THREAD

**Issue by FredM67** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#148]
When calling 
`curl -d "userId=xxx.yyy@live.fr&userPassword=zzzzzz" -H "Content-Type: application/x-www-form-urlencoded" -X POST https://ha101-1.overkiz.com/enduser-mobile-web/
enduserAPI/login`
I receive:
`{"success":true,"roles":[{"name":"ENDUSER"}]}`

There's no Cookie, how can I perform the second step ?

**Comment by rustysponge** [comment]
I stumbled across this as well and I guess, I figured it out: I save the cookie from the login request by adding "-c ./cookie" as parameter. Now, the cookie data is saved to a file .cookie and can be used with "-b ./cookie" in the next command.

**Comment by FredM67** [comment]
Thx for the advise.
In between, I simply re-type the gateway name, email and password in HomeAssitant-Overkiz, and it worked !! All without the whole procedure described here !
