### ISSUE TITLE
documentation of /exec/apply

### ISSUE THREAD

**Issue by hoyer77** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#15]
I try to open a Roller_Shutter. I know the DeviceURL and i know that i have a command like "open" on it.

In the Swagger-Doku as example of the exec/apply you have:

{
  "label": "string",
  "action": [
    {
      "deviceURL": "string"
    }
  ]
}

When i set label: "open" and the deviceURL i get 

    "error": "Bad parameters. (\"actions is not a table\")",
    "errorCode": "INVALID_PARAMETER"
    
Do you have an easy example how to set the command open to the deviceURL?

**Comment by an-mediola** [comment]
Something like the following worked for me, maybe you can get the idea from it, if you have `postman` you can use the import functionality to just make your request based on the curl request.  
````
curl --location --request POST 'https://gateway-1224-5722-0308.local:8443/enduser-mobile-web/1/enduserAPI/exec/apply' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer 626bd68b7cd25dccabfe' \
--data-raw '{
    "label": "OXIMO io - Set to 35% - TaHoma PC",
    "actions": [
        {
            "deviceURL": "io://1224-5722-0308/4792196",
            "commands": [
                {
                    "name": "setClosure",
                    "parameters": [
                        35
                    ]
                }
            ]
        }
    ]
}
````

**Comment by hoyer77** [comment]
Wow, your answer was quick. I have found that the "action" in the example is not correct. it must be "actions" and then with the "commands".

Thank you
