### ISSUE TITLE
Can't connect to local API even if developer mode ist active

### ISSUE THREAD

**Issue by Skirf** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#150]
Hi,

I wanted to make my HA a little bite more "local" and tried to connect to my switch via local api. I change from v2 box to switch for this feature.

Sadly I cannot connect via IP oder gateway-*PIN:8443 wit my credentials. Is there anything that could be the problem here? Do i have to open the Port manually in HA/Synology Container?

Thanks!

**Comment by Skirf** [comment]
Hi There,

both seems to work fine. Port 8443 is open and i get the 2024.4.3-12 response to the protocolVersion.

Well so maybe I have to finde someone with HA to get some further hints!

Thanks!

**Comment by BernoldNL** [comment]
You're welcome. Maybe you can close your issue, so that Somfy developers can focus on other issues?
