### ISSUE TITLE
Use a GUID-like unique identifier in addition to the deviceURL to identify the devices

### ISSUE THREAD

**Issue by octa22** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#18]
Hello,
thank you very much for the local API!
I have found out that the /setup/devices endpoint does not return the oid parameter unlike the cloud version.
Is is possible to return the oid with the each device description as well as the cloud API does?
Thank you very much!
Ondrej

the local version:
![image](https://user-images.githubusercontent.com/20907895/167936384-62ddeadd-ba92-4592-9b0b-13f5941603d0.png)

the cloud version:
![image](https://user-images.githubusercontent.com/20907895/167937048-ebe8fc07-5be6-45df-ad06-f30110d6031e.png)

**Comment by vhenriet-sfy** [comment]
Hello,

Why do you need such attribute?

**Comment by octa22** [comment]
Hello,
We use this as a unique identificator of the device in openHAB. Due to its "Guid" like string format it is much better than the deviceUrl attribute.
Thanks
Ondrej

**Comment by llavorel-somfy** [comment]
Hi @octa22 
As you noticed the local API does not provide any oid or other kind of GUID for the device. This is not an issue.
The DevMode relies only on the deviceURL.

**Comment by octa22** [comment]
Please @llavorel-somfy , can we reopen this issue and label it as an enhancement? I have already renamed it - this is the only action I am allowed to do with this issue (except adding a new comment)
The priority is up to you of course :-)
Thank you!

**Comment by dubocr** [comment]
> Hello,
> 
> Why do you need such attribute?

Hi,
Same problem here.
I choose to switch from UUID derived from `deviceURL` to `oid` several months ago, thinking that gateway migrations (causing deviceURL to change) will never impact user (as changing HomeKit UUID force user to recreate all automations associated with the linked device).

Having `oid` available on local API could help having a smooth transition. Please let us know if this is technically faisable (hope to see it in future) or not (then `deviceURL` will still be the best option to identify device)

Thank you.

**Comment by llavorel-somfy** [comment]
Hi

After additional discussion, we concluded that we won't work on this enhancement.
