### ISSUE TITLE
Wrong core:ClosureState or core:DeploymentState for io:AwningValanceIOComponent

### ISSUE THREAD

**Issue by tetienne** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#22]
Hi,

One end user of our Home Assistant integration reported an issue related to his io:AwningValanceIOComponent. The close and open state are reversed. After investigation, I notice something unusual within the device state returned:

```
         {
            "name": "core:ClosureState",
            "type": 1,
            "value": 80
          },
          {
            "name": "core:OpenClosedState",
            "type": 3,
            "value": "open"
          },
          {
            "name": "core:DeploymentState",
            "type": 1,
            "value": 80
          }
```

As you can see core:ClosureState and core:DeploymentState have the same value. Usually, they are complementary. Their sum is 100. 

Can you confirm their is something wrong? Thx

More context: https://github.com/home-assistant/core/issues/66857

**Comment by llavorel-somfy** [comment]
Hi @tetienne 

This is not an issue:
- Closure 100% means "there is no light coming through"
- Deployment 100% means "the fabric is totally deployed"
Therefore, it is coherent that the two states have the same value for an Awning Valance.

**Comment by tetienne** [comment]
Thx for your explanation. That's the first time I saw this use case. But now it make totally sense.
