### ISSUE TITLE
/setup/devices/controllables/{controllableName} is NOT working

### ISSUE THREAD

**Issue by Sjack-Sch** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#23]
End point: /setup/devices/controllables/{controllableName} is NOT working.

same response is received for:
/setup/devices/{deviceURL}/status
/setup/devices/{deviceURL}/status/{name}

Response:
{
  "error": "Unknown object.",
  "errorCode": "UNSPECIFIED_ERROR"
}

Response headers
 access-control-allow-headers: Authorization 
 access-control-allow-origin: * 
 content-length: 59 
 content-type: application/json 
 date: Tue,17 May 2022 19:26:22 GMT 
 server: KizOs

**Comment by vhenriet-sfy** [comment]
duplicate #7
