### ISSUE TITLE
Missing devices (Z-wave) on local setup

### ISSUE THREAD

**Issue by nyroDev** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#27]
I have several devices that are not returned in setup/devices in the local API.

In my case, I have 2 different kinds of missing devices :  
- zwave On/Off plug (Somfy) connected through the Zwave USB dongle
- Atlantic heating zones IO connected

Is there any plans to support these kinds of devices?  
Is there a roadmap available somewhere for this kind of question?

As an user (and dev), it's pretty frustrating to have a device just a step away and not be able to command it locally

**Comment by qelanhari** [comment]
https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/20
