### ISSUE TITLE
Compatible Boxes

### ISSUE THREAD

**Issue by AdyRock** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#3]
Is this API compatible with all the Somfy boxes, such as the Switch, Connexoon and the Connectivity Kit?

**Comment by qelanhari** [comment]
> *Eligible TaHoma Boxes: TaHoma V2, TaHoma switch, TaHoma DIN-Rail v1 & v2

**Comment by vhenriet-sfy** [comment]
Like @qelanhari said, only TaHoma V2, TaHoma switch, TaHoma DIN-Rail v1 & v2 expose the local api.

Thre is no developer mode on Connexoon and Connectivity Kit.
