### ISSUE TITLE
startIdentify and identify seems reversed

### ISSUE THREAD

**Issue by tetienne** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#30]
Hi,

I observed this behavior for various kind of covers. When calling the command `identify`, the cover wink until you call the method `stopIdentify`. When calling the command `startIdentify`, it does it few times and stop. 

I don’t know if it’s the expected behavior, but’s that’s not intuitive. When you start a command, you expect to call the stop command to... stop it. It’s why within our HA [component](https://github.com/iMicknl/ha-tahoma/blob/master/custom_components/tahoma/button.py#L23) we switch these commands.

**Comment by tetienne** [comment]
Hi, any feedback?

**Comment by llavorel-somfy** [comment]
Hi @tetienne 
What type of covers are you using ?
We are not sure to really understand what you are missing. The `identify `command is not enough for covering your use case ?

**Comment by tetienne** [comment]
Well, `identify` and `startIdentify` looks like reversed. `identify` should wink for few seconds only.
