### ISSUE TITLE
RTS dimmers not dimmable

### ISSUE THREAD

**Issue by OverSoft** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#33]
There's no option to dim RTS dimmers. (Like using the scrollwheel on an RTS remote)

The commands are:
                    {
                        "nparams": 0,
                        "commandName": "stop",
                        "paramsSig": "*p1"
                    },
                    {
                        "nparams": 1,
                        "commandName": "myWithTimer",
                        "paramsSig": "p1"
                    },
                    {
                        "nparams": 0,
                        "commandName": "down",
                        "paramsSig": "*p1"
                    },
                    {
                        "nparams": 1,
                        "commandName": "onWithTimer",
                        "paramsSig": "p1"
                    },
                    {
                        "nparams": 0,
                        "commandName": "up",
                        "paramsSig": "*p1"
                    },
                    {
                        "commandName": "test",
                        "nparams": 0
                    },
                    {
                        "commandName": "off",
                        "nparams": 0
                    },
                    {
                        "commandName": "on",
                        "nparams": 0
                    },
                    {
                        "nparams": 0,
                        "commandName": "my",
                        "paramsSig": "*p1"
                    },
                    {
                        "commandName": "identify",
                        "nparams": 0
                    },
                    {
                        "nparams": 0,
                        "commandName": "openConfiguration",
                        "paramsSig": "*p1"
                    },
                    {
                        "nparams": 0,
                        "commandName": "rest",
                        "paramsSig": "*p1"
                    }

None of these allow dimming, except (obviously) for "my" (which is the same as "rest" and "stop") which uses the preset (by the user) dimming position.
However, it is obviously possible to dim, since the remote can send small steps up and down.

I've tried all the lighting options in the Tahoma app to add this fixture, but none of them allow dimming.
Is it possible to add dimming to the Tahoma app and API? It's simply a missing feature.

**Comment by llavorel-somfy** [comment]
Hi @OverSoft 
What is the "controllable" of your device ?

**Comment by OverSoft** [comment]
The "controllableName" is "rts:LightRTSComponent".

**Comment by OverSoft** [comment]
@llavorel-somfy 
An alternative would be to allow a user to send a manual RTS command (like rfxcom allows you to do). It’s then possible to “step up” and “step down” the dimmer.

**Comment by llavorel-somfy** [comment]
Hi @OverSoft 
Indeed this controllableName does not provide dimming capabilities. We will work on providing such feature (on the new TaHoma app).

**Comment by llavorel-somfy** [comment]
Hi @OverSoft 

Your product should be typed as "rts:DimmableLightRTSComponent". Using the TaHoma App, you can delete and add again the product to be in the good definition and get those capabilities.
