### ISSUE TITLE
/exec/apply delivers http error 415 (unsupported mediatype) if charset is defined in content-type

### ISSUE THREAD

**Issue by ChristianRiedl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#35]
I am currently implementing a .NET version of the Tahoma (local) API. I got an unsupported mediatype error on "/exec/apply".
The reason was the charset parameter of the "application/json" content type which is created by default in .NET.

Usually the ContentType header allows to specify also a character set (like charset=UTF-8).
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

I was able to implement a work arround, but I think the Tahoma server (new Tahoma Switch) should accept a charset parameter for the content type.

**Comment by Numerato** [comment]
Thanks, I bumped into the same problem, searched hours for problems in my json syntax.
Devs, please fix this problem.

I used this C# code as a workaround to change header "Content-Type : application/json; charset=utf-8"
"; charset=utf-8" needs to be removed or the API call will fail.

`jsonData.Headers.ContentType` = MediaTypeHeaderValue.Parse("application/json");`

**Comment by yarwoob** [comment]
I have a problem with this as well.  It's stopping my integration working and there is no work around.  Please include in the next release.

**Comment by lacagithubuser** [comment]
I have the same problem. Loxone also tails "charset=utf-8" to the Content-Type row, causing "414 Unsupported Media Type" error.
Please fix it, otherwise we cannot offer Somfy shutters for our installations!

**Comment by lacagithubuser** [comment]
Are there any news about "414 Unsupported Media Type"  problem?

**Comment by vhenriet-sfy** [comment]
Fix will be available in the next release. (API version >= 2023.1)
