### ISSUE TITLE
Question: What is the intention of "Get Available Tokens"/ "Delete Token"

### ISSUE THREAD

**Issue by ChristianRiedl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#36]
Sorry I know it is a question, not an issue.
The only possibility to get a token is using "Generate a Token". "Get Available Tokens" delivers information about generated and activated tokens. Shall I store the tokens somewhere and reuse it instead of "Generate a token" ?

When should I "Delete a Token" ?

**Comment by vhenriet-sfy** [comment]
Hi,
You should keep your token and reuse it.

You only need to delete a token when you do not want to use it anymore, if you lost it or if its security has been compromised.

**Comment by ChristianRiedl** [comment]
Many thanks !!
