### ISSUE TITLE
Question: Token expiration and online requirement

### ISSUE THREAD

**Issue by nickngsr** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#37]
After obtaining a token from the cloud service it appears they have a 6 month expiry (according to the 'Get Tokens' response), I assume it is required for the Tahoma Switch / Din etc to have an internet connection in order to renew the token? If so is there a way to make tokens permanent until removed? Is it also possible to re-register the same token again in 6 months?

**Comment by an-mediola** [comment]
good question, it was my question too. We are working on something called local but then we are still dependent to outside (internet)

**Comment by nickngsr** [comment]
I have two concerns:

1. This is a mechanism that forces us to retain cloud credentials to renew tokens, or prompt users to re-enter them. Which is either a security concern or an inconvenience for the end user.
2. What capability does this have to be usable on a network with no internet connection (requiring an internet connection during initial set up could be forgiven)?

Is it possible to generate tokens locally (with either a specified or no expiry date) and have a physical button press validate permission - this is how Lutron LEAP and Philips Hue operate for example.

**Comment by llavorel-somfy** [comment]
Hi @nickngsr, @an-mediola,
We are going to work on fixing this issue. There should be no expiration.

**Comment by llavorel-somfy** [comment]
Released yesterday
