### ISSUE TITLE
Syntax for commands using local API

### ISSUE THREAD

**Issue by ParanoYak17** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#39]
Hello,

I was able to negotiate token and retrieve locally all the IO/RTS equipments thanks to new local API possibilities in dev mode.
However, I can't close rollers for instance. I try following command:
`curl -X 'POST' \
  'https://gateway-XXXX-XXXX-XXXX.local:8443/enduser-mobile-web/1/enduserAPI/exec/apply' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 62XXXXXXXX' \
  -H 'Content-Type: application/json' \
  -d '{
  "label": "string",
  "action": [
    {
    "deviceURL":"io:\/\/1203-6195-4820\/XXXXXXX",
    "commands":[
         {
            "commandName":"down",
            "nparams":0
         },
      ],
    }
  ]
}'`

Could you let me know what is the correct syntax to get this specific roller to close? I think documentation could be improved with some simple usage examples to give some additional guidance.

**Comment by an-mediola** [comment]
Probably this helps you :
https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/15#issuecomment-1115840769

**Comment by ParanoYak17** [comment]
Yes indeed, very helpful. It is working now. Thanks!
