### ISSUE TITLE
Cannot register (local) event listener

### ISSUE THREAD

**Issue by iMicknl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#4]
(first of all, thanks for providing a local API. This will make many Home Assistant + Somfy users happy).

I am working on integrating this local API in Home Assistant and thus [python-overkiz-api](https://github.com/iMicknl/python-overkiz-api/), but I am facing errors while registering the event listener. The same request works for the Overkiz cloud API.

```https://192.168.xx.xx:8443/enduser-mobile-web/1/enduserAPI/events/register```
```{"error":"Unknown object.","errorCode":"UNSPECIFIED_ERROR"}```

**Comment by AdyRock** [comment]
I'm getting error 400 when posting to:
'https://gateway-xxxx-xxxx-xxxx.local:8443/enduser-mobile-web/1/enduserAPI/events/register'

I can successfully get the devices from:
'https://gateway-xxxx-xxxx-xxxx.local:8443/enduser-mobile-web/1/enduserAPI/setup/devices'
so I believe the configuration is correct for local access.

**Comment by iMicknl** [comment]
Everything works here, except for the endpoint to register an event. Thus it seems that this endpoint is not included. The endpoint to fetch an event is present as well.

That’s also the reason why I reported this specific bug 😉.

**Comment by AdyRock** [comment]
I'm guessing we will have to wait for another firmware update on the boxes before this will work.

**Comment by AdyRock** [comment]
Any news on when the update will be available?

This issue is the only thing holding me back at the movement as it is key to the operation.

**Comment by iMicknl** [comment]
I can confirm that this is fixed in 2022.2.4-13. Thanks! 👍🏻
