### ISSUE TITLE
Token activated - not able to get even 'enduserAPI'

### ISSUE THREAD

**Issue by qmiloo** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#42]
Hi,

I'm totally new and my knowledge is also very basic. I'm using Tahoma DIN to my iO blinds
I went through all points in postman and it seems that i was able to register 'token' without any issues

![image](https://user-images.githubusercontent.com/48759219/178047462-3c860ad8-2cee-49c9-8cd1-fc47a7dda0ee.png)

Some time ago i was able to check everything via 'Swagger UI' but now  i'm not able even to see enduserAPI via 'Swagger UI' or 'Postman'

From 'Swagger UI' i can see below:

![image](https://user-images.githubusercontent.com/48759219/178046814-9f4963f8-7086-4358-86a3-726a5e0b664a.png)

and from Postman

![image](https://user-images.githubusercontent.com/48759219/178047115-195993c1-61b1-4ca4-8722-ebb9c2a5fdee.png)

I will add as well that i'm using as well Home-Assistant and i have no issues with using them via your integration.
I have as well different smart home installation (www.grenton.com) with additional 'HTTP Gate' module and i want to integrate my Tahoma directly with 'HTTP Gate' not via Home-Assistant that why i'm trying to get API

I would be very great full for any help

BTW - great job!

KR's
kamil

**Comment by BuBuaBu** [comment]
Hello,
When setting `Authorization` header, you should not set `<>` character. If your token is `01234567890123456789`, then the `Authorization` header must be `Bearer 01234567890123456789`

**Comment by qmiloo** [comment]
Hi,

Thank you for fast feedback

Now i have this

![image](https://user-images.githubusercontent.com/48759219/178057460-0a1adf63-b4ab-4c5c-b8a4-61174fd54909.png)

Should i go through all points once again to generate new token? If yes i did this 
There is possibility to use e.g. "uuid"?

thank you
kamil

**Comment by BuBuaBu** [comment]
Your token is valid, no need to regenerate a new one.

`/enduser-mobile-web/1/enduserAPI` is not a valid endpoint, you should try a reel one like `/enduser-mobile-web/1/enduserAPI/setup` to get the description of all your devices.

**Comment by qmiloo** [comment]
Working! Thank you so much!!

**Comment by qmiloo** [comment]
> Your token is valid, no need to regenerate a new one.
> 
> `/enduser-mobile-web/1/enduserAPI` is not a valid endpoint, you should try a reel one like `/enduser-mobile-web/1/enduserAPI/setup` to get the description of all your devices.

Sorry to going back to this topic but i need help again :(.
I'm able to discover all of my devices under tahoma but how correctly put device name if i want to see setup only for one?

Thank you in advance 
kamil
