### ISSUE TITLE
Question: How to post changes in parameters to more than one device?

### ISSUE THREAD

**Issue by qmiloo** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#43]
Hi,

Anyone can paste how you're managing to send request to more than one device in same script?

thank you in advance 

KR's
Kamil

**Comment by BuBuaBu** [comment]
You can execute multiple command with one POST request on /enduserAPI/exec/apply endpoint.

```
{
    "label": "Execute multiple commands",
    "actions": [
        {
            "deviceURL": "io://1234-5678-9012/1234567",
            "commands": [
                {
                    "name": "setClosure",
                    "parameters": [
                        12
                    ]
                }
            ]
        },
        {
            "deviceURL": "io://1234-5678-9012/7654321",
            "commands": [
                {
                    "name": "setClosure",
                    "parameters": [
                        24
                    ]
                }
            ]
        }
    ]
}
```

**Comment by qmiloo** [comment]
Hi,

Thank you for fast replay but unfortunately is not working

![image](https://user-images.githubusercontent.com/48759219/180862993-e44bf3d7-d979-41b1-b455-3231d11bb88b.png)

![image](https://user-images.githubusercontent.com/48759219/180863198-05548e17-e933-4043-91e9-df03d717f342.png)

**Comment by BuBuaBu** [comment]
you have missing comma `,` after deviceURL value

**Comment by qmiloo** [comment]
hahah, THANK YOU so MUCH!!
I'm really appreciate :)

all is working now
