### ISSUE TITLE
Login to retrieve Token seems to be blocked

### ISSUE THREAD

**Issue by abrocker** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#44]
Hello,

i have an issue since quite some time that i'm unable to retrieve a token via https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/login from my local Network. It always comes back with Bad Credentials. Once i switch to a Mobile Link i get authenticated and recieve a proper token. There is currently only the Tahmoa Switch in my Network communicating with Overkiz nothing else that could block it. I have tried this multiple times over a series of weeks. I'm working not based on a fixed IP.

Thoughts?
Philipp

**Comment by HenkRenting** [comment]
Same problem here with “bad credentials” too. I am 100% sure login credentials are correct, but the site says otherwise

**Comment by an-mediola** [comment]
Hi Dears,
I faced with that problem too, and it is because overkiz has many down times.
But just as a hint, if you have created a token for local usage, it will be valid for 6 months.
Then probably it would be better you store it somewhere. This will reduce the need to call overkiz to one time per 6 months.
Still it is not a solution but at least maybe it works for you too.
Somfy is going to remove the token expiration time too.
#37

**Comment by AdyRock** [comment]
I have a few user of my app experiencing this problem. The reply error code is either 401 or 502 on different attempts. The app retries every 30 seconds for 4 attempts and then waits 15 minutes before repeating.

The app does cache the token but obviously they need t get it initially. Hopefully the server reliability can be improved.

**Comment by abrocker** [comment]
The weird thing is  witht he Tahoma APP it's not an issue from Mobile outside of my Network but from within my Network it get's blocked.

**Comment by AdyRock** [comment]
Sounds like some sort of IP filter/ block.

**Comment by HenkRenting** [comment]
I don’t have the same experience. Logging on to the sote doesn’t work from either my home connection (NL KPN fiber) or mobile connections (NL Vodafone and NL KPN). If it would be a IP filter/block, wouldn’t we expect another error than invalid credentials? That’s the error I keep getting now.

**Comment by llavorel-somfy** [comment]
@abrocker @HenkRenting 
Indeed, you might have been temporarily IP-banned. 
Please do not consider this error message as an issue, this is the inteded behavior.

**Comment by abrocker** [comment]
@llavorel-somfy this is not a temporary ban. We would not have opened this thread if it would only be for 24 or 48hours.
