### ISSUE TITLE
 "error": "Bad parameters. (\"actions is not a table\")",

### ISSUE THREAD

**Issue by Sp1r1tus** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#45]
Hi!

how can i execute this command. I want to open my awning with this command. 

Documentation https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/blob/main/docs/openapi.yaml on line 235 --> todo finish

https://gateway-xxxx-xxxx-xxxx.local:8443/enduser-mobile-web/1/enduserAPI/exec/apply

Post with correct Bearer Token!

content-type: application/json

Body raw - json:
{
  "label": "label of the device",
  "action": [
    {
      "deviceURL": "io%3A%2F%2F1111-2222-3333%2F1234567"
    }
  ]
}

thx!

**Comment by adriweb** [comment]
See https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/15#issuecomment-1115840769

**Comment by Sp1r1tus** [comment]
thx for your quick answer and sorry for not issue double check
