### ISSUE TITLE
Somfy Connectivity Kit compatible with Developer Mode?

### ISSUE THREAD

**Issue by rmonius** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#46]
Hi, I cannot find the link in my account side for activating the developer mode. Could it be the Connectivity Kit is not compatible?
Best regards
Ralf

**Comment by llavorel-somfy** [comment]
There is already an enhancement request for this : https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/12
