### ISSUE TITLE
IoCommandTotalIncoherence

### ISSUE THREAD

**Issue by Snappy01** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#47]
Hello, 

i'm trying to control the Slate orientation, ( command is available on my device ) 

I send this : 

{

"label":"newOrientation",

"actions":[
{
"deviceURL":"io://1001-9030-4334/1233172",
"commands":[{"name":"setOrientation","parameters":[45]}]

}
]
}

But nothing happen, and when i fetch the event i've got this error : 

{
        "command": {
            "parameters": [
                45
            ],
            "command": "setOrientation",
            "execId": "164f0996-a686-41ea-9626-b11785a4ce43",
            "deviceURL": "io://1001-9030-4334/1233172",
            "state": "FAILED",
            "rawError": {
                "result": -254,
                "detailedError": "basicInfo=58;IoCommandTotalIncoherence"
            },
            "failureType": "UNKNOWN_ERROR",
            "rank": 0
        },
        "execId": "5a199211-5e91-4929-be7f-b225389fbea0",
        "name": "CommandExecutionStateChangedEvent"
    },
    {
        "failureType": "UNKNOWN_ERROR",
        "oldState": "INITIALIZED",
        "execId": "5a199211-5e91-4929-be7f-b225389fbea0",
        "rawError": {
            "result": -254,
            "detailedError": "basicInfo=58;IoCommandTotalIncoherence"
        },
        "name": "ExecutionStateChangedEvent",
        "newState": "FAILED"
    }

What does IoCommandTotalIncoherence mean ? 

When i check the device, the attribute command "setOrientation" is present, and i can control it using the app. 

Any idea ? is the Value must be between 0-100 or another value ? 

Thank you in advance for your help

**Comment by llavorel-somfy** [comment]
Hi @Snappy01 
You are apparently using a model of Exterior Venetian Blind which returns this error message when you try to set the orientation when the actuator cannot do so. Two options for you:

1. Change the position of the blind before setting the orientation
2. Use the "setClosureAndOrientation" command

**Comment by Snappy01** [comment]
Hello, 

i'll give a try. at this time the orientation work, even if the issue appears on the reply. 

Thank you for your feedback
