### ISSUE TITLE
What about Connexoon devices?

### ISSUE THREAD

**Issue by ljpaff** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#48]
Good afternoon,

I am the proud (or not) owner of a solution based on connexoon device. Until about a month ago I could use the remote API to access my equipment and thus be able to control both blinds and awnings (In total I have 9 motors).

The question that arises is that you have disabled the remote API for these devices and on the web you can not enable the "Developer Mode" option so I currently have an expensive paperweight with no third parties access.

Please, can you give us some solution to the people who have this device?. Since the new "Tahoma" application makes use of an API.

**Comment by llavorel-somfy** [comment]
There is already an enhancement request for this: https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/9
