### ISSUE TITLE
I can't create a developer account

### ISSUE THREAD

**Issue by julius-fpl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#49]
I want to create a new app to development.somfy.com but I can't because the website said: "Your developer status is marked as inactive. Even though the credentials below may appear active, you will not be able to use them until an administrator has activated your account."

How can I activate my account? 

I have build me a Led Color strip. I can control them with my own Android App and I want that the shutter is going to close when I switch the Led on in the App.
How can I close the shutter with the local Tahoma Api?

**Comment by julius-fpl** [comment]
I have generated the token and activate it. Now I can read out the apiVersion via Postman with the Bearer token. How can I shutdown now my shutter?

**Comment by adriweb** [comment]
See https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/15#issuecomment-1115840769

**Comment by julius-fpl** [comment]
Thank you. I will try it tomorrow.
Where can I find the dives id from my shutter?

**Comment by adriweb** [comment]
> Where can I find the dives id from my shutter?

With the [`/setup/devices` endpoint](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/blob/main/docs/openapi.yaml#L128)

**Comment by julius-fpl** [comment]
Thank you! It works fine. The Bearer token is active for 14 days, isn't it? And then I have to generate a new or how long can I use the token?
