### ISSUE TITLE
(self-signed) SSL cert uses the wrong common name

### ISSUE THREAD

**Issue by iMicknl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#5]
Following https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode#tls-certificate, I try to validate the connection by using the [Overkiz root ca](https://ca.overkiz.com/overkiz-root-ca-2048.crt), however this won't work.

In my debugging session, it seems that the certificate is for `xxxx-xxxx-3293.local`, while `gateway-xxxx-xxxx-3293.local` is used as hostname. 

<img width="490" alt="Screen Shot 2022-04-07 at 16 06 48" src="https://user-images.githubusercontent.com/1424596/162218939-851a9ebc-23c1-4aa3-9358-8c3adf67caf2.png">

I am using `aiohttp` (Python) to verify the connection and CA and I can reproduce that it works when I add `xxxx-xxxx-3293.local` to my host file, pointing to `gateway-xxxx-xxxx-3293.local`. At this point it will verify that my connection is correct. 

For now I will see if we can just verify the root CA, however it would be great if the cert was pointing to the right hostname.

**Comment by iMicknl** [comment]
Any update? Is this something that will be supported in a feature update? (See https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/25 for a similar request).

Otherwise I will hardcode that SSL should not be verified.

**Comment by AdyRock** [comment]
Any update, as I have user also finding the certificate problem?
Strange that is doesn't affect me or some other users even though we are all running the same code on the same platform.

**Comment by AdyRock** [comment]
I'm definitely verifying the certificate. It seems my Tahoma has several ALT names so it works with both the gateway and non-gateway names. 
I have now added the work around shown in #25 and it is working for the users that reported the issue and still works for me.

My code is on my github https://github.com/AdyRock/com.somfy.tahoma.

Currently I have released it to the Homey store in the test stream, so limiting the number of users.

**Comment by iMicknl** [comment]
@llavorel-somfy @vhenriet-sfy any update?

**Comment by iMicknl** [comment]
Any update? I am currently working on the Home Assistant implementation, and I rather not disable SSL verification.

**Comment by iMicknl** [comment]
@llavorel-somfy @vhenriet-sfy is this a bug that you plan on fixing, or is this a wontfix?

**Comment by llavorel-somfy** [comment]
Hi @iMicknl we have deployed new certificates, would you be able to test again ?

**Comment by iMicknl** [comment]
@llavorel-somfy thanks! Should this be applied automatically, or does it need a restart / reset?

**Comment by iMicknl** [comment]
Works like a charm with `https://ca.overkiz.com/overkiz-root-ca-2048.crt`! Thanks a lot, @llavorel-somfy.
