### ISSUE TITLE
States device endpoint not working 

### ISSUE THREAD

**Issue by tomvandeputte** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#51]
Hello,

I'm trying to consume the api.

The following endpoins are working as expected:
1) https://{localIp}:8443/enduser-mobile-web/1/enduserAPI/setup/devices

2) https://{localIp}:8443/enduser-mobile-web/1/enduserAPI/setup/devices/io%3A%2F%2F2018-4112-2800%2C216201

So the used deviceUrl is correct. But retrieving the states is not working unfortunately:
https://{localIp}:8443/enduser-mobile-web/1/enduserAPI/setup/devices/io%3A%2F%2F2018-4112-2800%2C216201/states

I receive the following Api Exception: 
The HTTP status code of the response was not expected (400).

Status: 400
Response:
{"error":"Unknown object.","errorCode":"UNSPECIFIED_ERROR"}

Any idea about this? 

When checking the state information (in device api call) the following statse are available:
"states": [
        {
            "type": 6,
            "name": "core:MovingState",
            "value": false
        },
        {
            "type": 3,
            "name": "core:StatusState",
            "value": "available"
        },
        {
            "type": 1,
            "name": "core:Memorized1PositionState",
            "value": 105
        },
        {
            "type": 1,
            "name": "core:TargetClosureState",
            "value": 0
        },
        {
            "type": 11,
            "name": "core:ManufacturerSettingsState",
            "value": {
                "current_position": 0
            }
        },
        {
            "type": 3,
            "name": "core:OpenClosedState",
            "value": "closed"
        },
        {
            "type": 1,
            "name": "core:DeploymentState",
            "value": 0
        },
        {
            "type": 3,
            "name": "core:DiscreteRSSILevelState",
            "value": "good"
        },
        {
            "type": 1,
            "name": "core:RSSILevelState",
            "value": 88
        },
        {
            "type": 3,
            "name": "core:NameState",
            "value": "my device"
        }
    ]

**Comment by BuBuaBu** [comment]
Duplicate #7

**Comment by tomvandeputte** [comment]
Oops overlooked that one. So it will be fixed next release. Can we find somewhere the release dates?
