### ISSUE TITLE
Tahoma local API - token from ha101-1.overkiz.com not accepted

### ISSUE THREAD

**Issue by Gr3g88** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#52]
I'm at a loss and hoping someone might be able to help as my tahoma v2 is refusing to play ball!

I have generated and activated a token as per the documentation and can see that the activation is successful through the get available tokens request...so far, so good.

When I attempt to pass the UUID to the tahoma device in the header of the request I am greeted with a 401 unauthorized response. I can pull the version from the local API, however any function that requires the authorisation bearer in the header returns 401... which im assuming suggests that the tahoma box is not acknowledging active tokens registered via ha101-1.overkiz.com - does anyone have any ideas what might be going on and how I can get my tahoma box to respond?

Using (gateway id replaced with example): 
`curl -X 'GET' \ 'https://gateway-2001-0001-1891.local:8443/enduser-mobile-web/1/enduserAPI/setup/devices' \ 
-H 'accept: application/json' \ 
-H 'Authorization: Bearer ae5224d0-7805-4a2d-88bf-15424f548e17'
`

**Comment by stefaanv** [comment]
Same thing here.
- Token generation successful, I'm able to request (2) generated tokens
- Getting the API version works (url https://192.168.0.120:8443/enduser-mobile-web/1/enduserAPI/apiVersion) - this call this works when the authorization is removed
- Any other local API call fails with 401status `{"error": "Not authenticated.","errorCode": "RESOURCE_ACCESS_DENIED"}`
I'm using postman for API testing

I guess something's missing in the documentation

**Comment by stefaanv** [comment]
@Gr3g88 
Found the problem
Instead of using the UUID in the bearer token authorization, you have to use the token that got sent in the `token activation` step.  It's a 20 characters hex string without dash (-) signs
The documentation is not very clear about this

**Comment by Gr3g88** [comment]
@stefaanv - this worked, you're a superstar!
