### ISSUE TITLE
Multicast not working on all machines

### ISSUE THREAD

**Issue by MikeyMan83** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#54]
Hi there!

Is it an idea to rethink the whole multicast thing? From a synology nas it's nigh on impossible to access a .local address.
And the local ip works just as well. Or even better i must say :)'

Only issue i have now with direct IP access is that i'm getting error connection refused after a while. But that seems to be a software setting of some sorts.

**Comment by adriweb** [comment]
I've had no issues using Bonjour-exposed devices with .local before in my synology NAS 🤔

**Comment by MikeyMan83** [comment]
> I've had no issues using Bonjour-exposed devices with .local before in my synology NAS 🤔

No clue what's happening there. Bonjour is turned on. Not apart from that. It's unnecessarily complex.

**Comment by adriweb** [comment]
Sounds like an issue on your network side/config. Enabling Bonjour on the synology itself is for making it discoverable with .local but that's not related to what you want though.
Anyway as a workaround I guess it doesn't matter much if you make your router assign a specific IP to your gateway.

**Comment by MikeyMan83** [comment]
It can't be network related. Every other machine apart from the Synology is able to resolve the address...

**Comment by MikeyMan83** [comment]
Tried to manually open the mdns / bonjour ports, but to no avail. Think it might be down to the libnss-mdns missing.

**Comment by vhenriet-sfy** [comment]
if mdns is not working, you can still assign a static ip to the TaHoma.

**Comment by MikeyMan83** [comment]
@vhenriet-sfy No clue why so difficult on the internal network tbh. Direct access could and should be much easier than it currently is.
