### ISSUE TITLE
Somfy Connected thermostat

### ISSUE THREAD

**Issue by kvanhoey** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#56]
Hello,

Slightly off-topic feature request here.

I've been using the Somfy Connected thermostat through it's dedicated (non-Tahoma) gateway. 
I used to be able to integrate it in HomeAssistant through the Somfy integration (which was using the former API). Since this API is being sunset in favor of Overkiz, this doesn't work anymore. And Overkiz doesn't cover the dedicated Somfy thermostat.

It's disappointing to see such a critical feature disappear, because it was one of the reasons I chose this thermostat.
Is there any hope to see an integration of the Connected thermostat in Overkiz soon? 

Thanks

**Comment by tetienne** [comment]
@kvanhoey That's more a topic for Home assistant rather Somfy.

I was the code owner of the Somfy integration and one of the Overkiz integration. The Somfy Thermostat has been added few months ago and should be supported.

**Comment by iMicknl** [comment]
@tetienne I believe that @kvanhoey does not have any Overkiz hub. The connected thermostat has a direct connection to the cloud, and previously this did work with the Open with Somfy API.

**Comment by kvanhoey** [comment]
Hi both, and thanks for your help.

> @kvanhoey That's more a topic for Home assistant rather Somfy.
Sure, I agree. I first asked [there](https://community.home-assistant.io/t/somfy-thermostat-feature-request/265477/8?u=kvanhoey), and they suggested I ask this here ... so I'm trying my luck.

> I was the code owner of the Somfy integration and one of the Overkiz integration. The Somfy Thermostat has been added few months ago and should be supported.
If I understand correctly, you're saying that Overkiz supports the Somfy Connected Thermostat, which then would mean that it's the [Overkiz Integration in HomeAssistant](https://www.home-assistant.io/integrations/overkiz/) that hasn't supported it yet? If so, I'll question and look into it on that side...

Cheers

**Comment by iMicknl** [comment]
@kvanhoey to clarify, do you have an Somfy TaHoma hub? Or is your thermostat directly connected to the internet? (and did that work in the past with the Somfy API).

**Comment by kvanhoey** [comment]
I have NO TaHoma hub: my connected thermostat is directly connected to the internet.

And yes: before sunsetting the Somfy API, I was able to integrate it in HomeAssistant through the Somfy integration.

**Comment by kvanhoey** [comment]
Any news? I still believe that it's not available in Overkiz since it's a standalone thermostat with direct cloud access. Therefore I believe its a Somfy issue, and not a HA one. Happy to hear if I am wrong @tetienne?

**Comment by kvanhoey** [comment]
Hello. Thanks for the answer and for sharing to the appropriate team.

Please keep me up to date if there's any improvement: I bought this thermostat exactly because I could connect it to my HomeAssistant, so this feature falling away is quite painful.

Regards

**Comment by RomainBoreli** [comment]
Hello, I have exactly the same product (somfy radio connected thermostat) and so I have the same problem. If anyone has any ideas, I'd be very grateful :)

**Comment by Roboreli** [comment]
Hello, I have exactly the same product (somfy radio connected thermostat) and so I have the same problem. If anyone has any ideas, I'd be very grateful :)

**Comment by kvanhoey** [comment]
I had no news since my request and am still in the same situation, namely quite disappointed about buying something exactly for a feature that was sunset afterwards :(. I genuinely hope for a workaround soon.
