### ISSUE TITLE
Somfy Protect - Virtual Alarm - Not available in local API

### ISSUE THREAD

**Issue by jiams95** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#58]
Hi team, 
My main usage of Somfy is tied to the Somfy Protect Alarm (called Virtual Alarm in Cloud API). 
This object is not returned by local API and so we can't control it through local API. 
Can you please fix this issue and allow Somfy Alarm to be controlled through local API as well?
Thanks.

**Comment by llavorel-somfy** [comment]
Hi @jiams95 
The Developer Mode only allows controlling of a range of devices that communicate directly through various radio protocols with the TaHoma Box. This is not the case for the Somfy Protect Alarm which is communicating with its own infrastructure.
Therefore, I am afraid that we can't positively answer to this demand.
