### ISSUE TITLE
Problem for Tahoma Developer API Access

### ISSUE THREAD

**Issue by remy-lavabre** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#62]
Hi, This is my problem :

I have activated the developer mode on my Somfy account (Tahoma Box). No problem

However when I use the link:

https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI...;,

I ALWAYS get the same response:

"This site is inaccessibleThe web page at https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/ may be temporarily inaccessible or may have been permanently moved to a other web address.
ERR_INVALID_RESPONSE"

And this regardless of the time and the browser used. So impossible to recover the cookie, token etc... It blocks me FROM THE START.

If I use the second link supposed to be used after the first:

https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI...

I get the response:

"{"errorCode":"RESOURCE_ACCESS_DENIED","error":"Not authenticated"}"

Is there something I am doing wrong or is the problem with Somfy?
How do I use this Developer API?

Thank you very much for your help !

**Comment by remy-lavabre** [comment]
Yess ! Thank-you, I've already read it and it is exactly what I am doing : 
https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/MYLOGIN
obviously I replace MYLOGIN with my real somfy login... :-)

Ad the answer is ALWAYS the same thing : 
Ce site est inaccessible. Il se peut que la page Web à l'adresse https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/MYLOGIN soit temporairement inaccessible ou qu'elle ait été déplacée de façon permanente à une autre adresse Web.
ERR_INVALID_RESPONSE

![SOMFY](https://user-images.githubusercontent.com/82585707/195389477-76b6c3b7-5495-4b92-80a1-58abb79715f7.png)

**Comment by llavorel-somfy** [comment]
@remy-lavabre, several things:
- You have to use the POST method, you cannot simply make the appropriate API call from the search bar of your browser
- Do not change the URLs we documented, unless it includes a variable (like `{{url}}`)
- You have to include your userId and userPassword in the body of your request using x-www-form-urlencoded

**Comment by remy-lavabre** [comment]
Thank you for yor help but i still don't understand... ! :-(

-1/ I tried
curl -X POST https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/MYLOGIN
and i got the answer :+1: 
{"errorCode":"RESOURCE_ACCESS_DENIED","error":"Not authenticated"}

-2/ you said "You have to include your userId and userPassword in the body of your request using x-www-form-urlencoded"
But in the doc it is saying : Method: POST : https://{{url}}/enduser-mobile-web/enduserAPI/login
and nothing about userPassword for the POST...

-3/ Could you give me could you give me a precise example of the exact syntax under linux to pass the POST stage, it would be easier for me because I can't do it, and I don't understand either "using x-www-form- urlencoded"...

Thank you very much for your appreciated help.

**Comment by remy-lavabre** [comment]
and if I use : POST https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/MYLOGIN
the answer is : "Please enter content (application/x-www-form-urlencoded) to be POSTed:"
What must I do then ??
Thank-you

**Comment by llavorel-somfy** [comment]
```
POST /enduser-mobile-web/enduserAPI/login HTTP/1.1
Host: ha101-1.overkiz.com
Accept: application/json, text/javascript, */*
Content-Type: application/x-www-form-urlencoded

userId=YOUR_USERID&userPassword=YOUR_USERPASSWORD
```

**Comment by remy-lavabre** [comment]
Yes thank you, I made good progress!

I got now the message:
<!doctype html><html data-adblockkey="hgfhgf..........etc. etc."href="https://parking.bodiscdn.com" crossorigin></head><body><div id= "target" style='opacity: 0'></div><script>window.park = "dfgdfghdfhdf.....etc.etc.
but no cookie JSESSIONID contrary to what I understand from your documentation...

Is the data-adblockkey only the important thing of the message ???

Would it be possible for you to provide me, as before, with a CLEAR example of the sequence of operations to be carried out next for the method GET (GENERATE A TOKEN) and POST (ACTIVATE YOUR TOKEN) and GET (GET AVAIBLE TOKEN) because I would never have found by myself without your help with the only documentation of Somfy APIs...

In addition I think it should also be useful to others who will may be themselves in the same case...

Thanks again

**Comment by llavorel-somfy** [comment]
We believe it is clearly documented @remy-lavabre :
![image](https://user-images.githubusercontent.com/29543219/195816474-f443127f-88f6-4096-8994-d1f7a0218f8b.png)

I don't know what the `data-adblockkey` refers to ...

The Cookie is returned in the response headers of your http request.

**Comment by remy-lavabre** [comment]
Yes Thank-you, you're right.

Could you confirm that the POST method is tu use in an Linux terminal ?
Because I did not have cookie, only the answer I give you last time...

Can you send me the detailed list of operations to be carried out for the future as you did previously?
It helped me a lot and allowed me to manage, without it I can't do it.
Thanking you

**Comment by Sirus10** [comment]
Hello, 

since few weeks (May 24th 2023) autentification is not working anymore on this API. 
I am looking for any update of published changes but I cannot seen any. 

Does any of you awayre og a new API remplacing this one ? 

 POST-> https://ha110-1.overkiz.com/enduser-mobile-web/enduserAPI/login | userId=****&userPassword=**** : 401


I have ony 401 result . 


Thanks for your feedback !
