### ISSUE TITLE
Problème thermostat somfy

### ISSUE THREAD

**Issue by tthma** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#63]
Bonjour
Quand je change la température sur l’application thermostat somfy le plugin prend en compte le changement uniquement si je vais sur l’application tahoma ou le site internet que ça mette à jour la valeur du set point 

cordialement

**Comment by llavorel-somfy** [comment]
Bonjour tthma,
Ce projet GitHub concerne l'utilisation du Developer Mode des box TaHoma. Pour les problèmes liés à l'utilisation de l'application Somfy je vous conseille de vous rapprocher de notre assistance via le forum d'entraide: https://forum.somfy.fr/.
