### ISSUE TITLE
Could not add new App

### ISSUE THREAD

**Issue by harald73** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#67]
I enabled the developer mode, logged into developer.somfy.com and tried to add a new app. This failed, I assume due to the message:

_Your developer status is marked as inactive. Even though the credentials below may appear active, you will not be able to use them until an administrator has activated your account._

Please advice, how to activate my account
thx

**Comment by llavorel-somfy** [comment]
Hi @harald73 
App creation from developer.somfy.com has been shut down with the previous service Somfy Open API.
It is not needed to use the Developer Mode, please follow the documentation [here ](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode)
