### ISSUE TITLE
Possible values of core:MeasuredValueType

### ISSUE THREAD

**Issue by tetienne** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#68]
Hi,

Can we have a list of all the existing values of core:MeasuredValueType?

**Comment by vhenriet-sfy** [comment]
Hi @tetienne
here is the list:
core:AbsoluteValue
core:AngleInDegrees
core:AngularSpeedInDegreesPerSecond
core:ElectricalEnergyInKWh
core:ElectricalEnergyInWh
core:ElectricalPowerInKW
core:ElectricalPowerInW
core:ElectricCurrentInAmpere
core:ElectricCurrentInMilliAmpere
core:EnergyInCal
core:EnergyInkCal
core:FlowInLitrePerSecond
core:FlowInMeterCubePerHour
core:FlowInMeterCubePerSecond
core:FossilEnergyInWh
core:GradientInPercentagePerSecond
core:LengthInMeter
core:LinearSpeedInMeterPerSecond
core:LuminanceInLux
core:PartsPerBillion
core:PartsPerMillion
core:PartsPerQuadrillion
core:PartsPerTrillion
core:PowerPerSquareMeter
core:PressureInHpa
core:PressureInMilliBar
core:RelativeValueInPercentage
core:TemperatureInCelcius
core:TemperatureInKelvin
core:TimeInSecond
core:VectorCoordinate
core:VoltageInMilliVolt
core:VoltageInVolt
core:VolumeInCubicMeter
core:VolumeInGallon
core:VolumeInLiter

**Comment by tetienne** [comment]
That was fast. Thx!

**Comment by tetienne** [comment]
@vhenriet-sfy Can you confirm or not, that all the sensors are exposing this attributes?
