### ISSUE TITLE
Question: Can TaHoma Switch run a 3rd party program?

### ISSUE THREAD

**Issue by PeruGA** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#69]
I'm trying to develop a program a bit too complex to do it directtly in the TaHoma app. Is it possible to run it directly in he switch or do I need another device to run it?

**Comment by vhenriet-sfy** [comment]
Only REST API is available. You cannot execute your own code in the TaHoma.

**Comment by PeruGA** [comment]
Thanks!
