### ISSUE TITLE
Response for invalid listener ID

### ISSUE THREAD

**Issue by JanJaapKo** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#70]
Hi,

I'm polling the Somfy box for state updates on the `/events/{listenerId}/fetch` endpoint. According the documentation on the `/events/register` endpoint, the lifetime of the listener is indefinite until reboot of the box or more than 10 minutes of inactivity. Is there a specific response when the listener is not valid anymore so I can automatically register a new one?

**Comment by adriweb** [comment]
I guess the HTTP code would be 404, or at least not 200?

**Comment by JanJaapKo** [comment]
Well I would guess so to, but the point of documentation is to avoid guessing ;)

**Comment by vhenriet-sfy** [comment]
Hi,
Api return with a HTTPCode `400` and an object like : `{"error":"\"No registered event listener.\"","errorCode":"UNSPECIFIED_ERROR"}`
