### ISSUE TITLE
Please add more info in OpenAPI for commands

### ISSUE THREAD

**Issue by JanJaapKo** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#76]
All devices specifiy there supported commands on the `setup/devices` endpoint. Some commands require additional parameters. Can you in the openAPI document describe the meaning of the required parameters?

**Comment by llavorel-somfy** [comment]
Hi @JanJaapKo 

We would prefer that you ask for direct and precise questions of commandas and parameters that you seek. We will let you open another issue if needed
