### ISSUE TITLE
List of all values for field 'controllableName'

### ISSUE THREAD

**Issue by kvanisterdael** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#77]
Is there a list available of all possible values for the field 'controllableName' and the corresponding products?
We would like to make an overview of which devices are supported.

**Comment by llavorel-somfy** [comment]
Hi @kvanisterdael 

We would prefer that you ask for direct and precise questions of controllableNames that you seek. We will let you open another issue if needed
