### ISSUE TITLE
Error Not authenticated for each API call

### ISSUE THREAD

**Issue by charles-edouard-bernaille** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#8]
Hi,
I successfully retrieved and activated my token to call local API
GET on /apiVersionis OK
But all other requests don't work and I retrieve 401 error, even if I added authorization header Bearer {{TOKEN}} with previously generated token
{
    "error": "Not authenticated.",
    "errorCode": "RESOURCE_ACCESS_DENIED"
}

What did I forget ?
Yhanks in advance

**Comment by iMicknl** [comment]
`/apiVersions` doesn't have authentication, thus that should be working when your authentication is not correct.

How do you build the request? Can you share your sample?

**Comment by charles-edouard-bernaille** [comment]
Thanks for quick reply.
Shame on me, whan I checked to send you a CURL request from my Postman, I found that my Authorization header contained twice 'Bearer'
With the correction, that's OK on my side
