### ISSUE TITLE
Problem with API Authentification

### ISSUE THREAD

**Issue by MaisonIUT** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#82]
Hello, 

I have the tahoma switch box and I have activate Developer mode. My tahoma is activate and is on connected mode.

But I can't use Developer mode and the API. 

When I go to the link, I error. You can see :
![image](https://user-images.githubusercontent.com/122619255/212339802-7a9626e5-738c-42ff-8863-ea8a46e28974.png)
 and 
![image](https://user-images.githubusercontent.com/122619255/212339873-30ac4961-b8fb-402b-8b42-ddb97bd73b30.png)

Can you help me ?

Thank you so much

**Comment by joepv** [comment]
With your first error you have to do a POST request. GET is not allowed as stated in the documentation ;)
