### ISSUE TITLE
[Asia / Oceania regions] Somfy Connexoon RTS

### ISSUE THREAD

**Issue by lucidph3nx** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#84]
Please Support enabling the local API for the 'Somfy Connexoon RTS' boxes that are used in the Australasia/Oceania Region.
From what I can tell these boxes are nearly identical to those in Europe but do not yet have the ability to enable the local api.

https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/9

**Comment by llavorel-somfy** [comment]
Hi @lucidph3nx do you still face the issue ?

**Comment by lucidph3nx** [comment]
@llavorel-somfy The issue is resolved, I have been able to enable developer mode (www.somfy.com.au) and successfully authenticate and use the device.

I recommend a small change to the docs to inform users that users of the Oceania devices need to authenticate and get their token using the alternate overkiz server (https://ha201-1.overkiz.com) or else they will not be able to successfully login.

Can I also just say, that I have been waiting for this for a long time and you have made me very happy this morning. Thank you so much!
