### ISSUE TITLE
Token lifetime

### ISSUE THREAD

**Issue by markdegrootnl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#85]
What is the Token lifetime for local access? 

Can I request a token once and expect it to work for ever? Also when the gateway restarts?

**Comment by iMicknl** [comment]
It should be never expiring, however I face the same issue as https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/83, where after an update, all tokens need to be recreated.

**Comment by vhenriet-sfy** [comment]
Duplicate #83
