### ISSUE TITLE
[Romania] Unable to activate developer mode on Connexoon box 

### ISSUE THREAD

**Issue by neugenn** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#86]
Hi everybody.
First of all, thank you very much for all the effort you put into bringing local API also on Connexoon.
I was very excited when I saw that a new version has been released (https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/9). I went straight to the TaHoma mobile app and updated my box (now running 2022.6.4-13 version).

Things started to get complicated when I tried to enable the local API support.
For some reason, I am unable to log in into  My Account (as described in the README)

This are the steps I take:

1. Go to www.somfy.com
2. Get redirected to regional site www.somfy.ro ; here I click on Somfy Connect
3. Get redirected to https://www.somfy-connect.com/ro/ when I input my credentials
4. Get redirected to https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/?userId=<ID>&ssoToken=<TOKEN> (I've removed the actual values of userId and ssoToken) where I get a pop up saying that "An error has occurred on the server"

I tried resetting the password, same thing happens.
TaHome mobile app works as expected.

Am I doing something wrong ?
Thank you !

**Comment by renx123** [comment]
Hey!

For Estonia there is also problem. When choose from somfy.com Estonia it redirects to local page but there is not even Login possibility. Also not possible to login through other country. Is there any another workaround to enable developer mode?

**Comment by neugenn** [comment]
Hi @renx123,
As a workaround, I've contacted local customer support and they were able to enable developer mode on my connexoon box.
