### ISSUE TITLE
developer status is marked as inactive on developer.somfy.com

### ISSUE THREAD

**Issue by r4780n3** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#88]
Hello, the developer mode of my connexoon box is activated but the creation of apps is not possible on the developper.somfy.com site.
What more do I need to do to activate it?
![devSomfyInnactiv](https://user-images.githubusercontent.com/55829296/217787025-2a6ac948-f547-4624-8216-bc98a1dd1c9e.png)

![devModeActivate](https://user-images.githubusercontent.com/55829296/217787545-e2b7f7e0-b252-4b21-ba9a-22802d7a4781.png)

**Comment by qelanhari** [comment]
No apps to create, just follow the instructions of the readme. If you have activated the dev mode, you just have to access the API (after creating credentials, using the doc bellow)
https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/blob/main/README.md

**Comment by r4780n3** [comment]
thanks for the answer but I just need to connect a plugin to jeedom following the instructions from the developer:
https://benjaminprevot.github.io/jeedom-plugin-connexoon/fr_FR/
the apps allows you to retrieve certain information to make the connection...

**Comment by qelanhari** [comment]
The Jeedom plugin is not using the local api and dev mode of the connexoon but the old public cloud api for developpers (which is deprecated)

**Comment by r4780n3** [comment]
There are 2 plugins, I use Connexoon not Tahoma. I therefore understand that it will not be able to work since it uses an old procedure?...

**Comment by r4780n3** [comment]
https://benjaminprevot-github-io.translate.goog/jeedom-plugin-connexoon/fr_FR/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp

**Comment by qelanhari** [comment]
In any case this plugin is not using the API concerned by this repo.
I suggest you look into the Tahoma plugin indeed. I am pretty sure they worked on the local version (this repo) also, but not sure if it's ready or not.

**Comment by r4780n3** [comment]
OK, thanks for the response and the time. I'll see how the other plugin works.
