### ISSUE TITLE
Connexoon support

### ISSUE THREAD

**Issue by barryhartman** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#9]
Hi Somfy developers,

Great news that a local api will be available. Is it possible to also support the Somfy Connexoon?

**Comment by benjaminprevot** [comment]
Hello Somfy,

Good news for the local API.

@barryhartman is right, Connexoon support will be very welcomed by lot of consumers.

Let's cross the fingers you will add this request in your backlog as soon as possible ;-)

Thanks

**Comment by OrbitingOcelot** [comment]
Yes please, as a customer I cannot understand why the hardware I bought (connexxoon) is not being supported by the local API. Somfy cloud API is having too many issues/limitations, please also enable local access on connexxoon!

**Comment by panic1** [comment]
Agreed, it has been a sincere disappointment to be unable to reliably use the open cloud API since I bought these Somfy covers. Please add this local API to the Connexoon as well.

**Comment by TroisSix** [comment]
Agreed, I am also waiting for the support of the Connexoon product :)

**Comment by woutf** [comment]
Same here. Please add Connexoon support

**Comment by Paul-Vdp** [comment]
Yes, please put also us Connexoon-users out of our misery ...

**Comment by Archcry** [comment]
I would also like to have local API support for connexoon. In the meantime you can jailbreak the connexoon using https://blog.unauthorizedaccess.nl/2021/04/07/no-clouds-just-sunshine.html

**Comment by OrbitingOcelot** [comment]
As this request is gaining traction:
Is there any Somfy product manager/owner etc. around, who could give us lowly customers/users some insight whether this request has been noticed by Somfy decision makers, and if there are any plans to pursue this? A brief update on this would be highly appreciated.

Also please consider how supporting a local API would increase your standing within the community, reduce the support contacts related to cloud/connection issues, and make existing customers happy.

**Comment by panic1** [comment]
> As this request is gaining traction: Is there any Somfy product manager/owner etc. around, who could give us lowly customers/users some insight whether this request has been noticed by Somfy decision makers, and if there are any plans to pursue this? A brief update on this would be highly appreciated.
> 
> Also please consider how supporting a local API would increase your standing within the community, reduce the support contacts related to cloud/connection issues, and make existing customers happy.

Not to mention: reduce the load on the cloud servers once the change has been implemented in the third party home control applications.  It has immediate relief for those customer who upgrade to the local API, and also for those that stay with the cloud API.

**Comment by Caros2017** [comment]
Local API would be greatly appreciated!

**Comment by plopez** [comment]
Would be great for all connexoon owners !

**Comment by posixx** [comment]
Please open up local API for connexoon! According to HA blog Somfy has decided to shut down its cloud API after June 21st, 2022. So we connexoon owners need the local api!

**Comment by iMicknl** [comment]
> Please open up local API for connexoon! According to HA blog Somfy has decided to shut down its cloud API after June 21st, 2022. So we connexoon owners need the local api!

The Home Assistant Overkiz integration will keep supporting Connexoon via the Cloud API; however I would love to see Connexoon offering a local API as well.

**Comment by OrbitingOcelot** [comment]
Cloud API is down again - I cant control my devices :(

Wish I had a local API to gain indenpence from these outages!

Logger: homeassistant.components.overkiz
Source: helpers/update_coordinator.py:223
Integration: Overkiz (by Somfy) ([documentation](https://www.home-assistant.io/integrations/overkiz), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+overkiz%22))
First occurred: 10:00:51 (1 occurrences)
Last logged: 10:00:51

Error fetching device events data: Server is down for maintenance.

**Comment by panic1** [comment]
Maybe Somfy will skip the local API in connexoon in favor of the [Matter](https://en.wikipedia.org/wiki/Matter_(standard)) integration?  Somfy is a member company working on that standard...

**Comment by neugenn** [comment]
Hi all. Any updates about this ?
Really looking forward to having local API support on Connexoon.
Many thanks !

**Comment by svefro** [comment]
Somfy told me it is never going to be supported due to hardware limitations.
I got a free Tahoma box from them after a lot of complaining

**Comment by thesebastianf** [comment]
@svefro how did you contact them? mail, phone, ..?

**Comment by svefro** [comment]
It is a long story :p i it all started on a contact form somewhere on the somfy website.
I live in norway and that helped since we have a 5 year warranty on consumer electronics.
The connexoon did not do what it did when i bought it so it was basicaly broken.

**Comment by barryhartman** [comment]
> Somfy told me it is never going to be supported due to hardware limitations.
> I got a free Tahoma box from them after a lot of complaining

Well I find that hard to believe since there is already a custom jailbreak available with local support (https://community.home-assistant.io/t/somfy-connexoon-tahoma-jailbreak/297076). However I don’t want to do this and expect decent local support from Somfy.

**Comment by Caros2017** [comment]
> > Somfy told me it is never going to be supported due to hardware limitations.
> > I got a free Tahoma box from them after a lot of complaining
> 
> Well I find that hard to believe since there is already a custom jailbreak available with local support (https://community.home-assistant.io/t/somfy-connexoon-tahoma-jailbreak/297076). However I don’t want to do this and expect decent local support from Somfy.
> 
> So please Somfy, come with an official statement regarding Connexoon local support?

Was looking for the same url. It's basically already built-in.

**Comment by OrbitingOcelot** [comment]
Not possible d/t Hardware is probably a very good standard line for the support to get rid of annoying customers.
I dont see how an ARM based design with a preexisting LAN port which is communicating with the cloud by default would be unable to open a socket for local communication, that would be truly astonishing :)

**Comment by svefro** [comment]
Yes but that is wat i was told.
This new api is missing a lot of documentation also. But i finally got it working

**Comment by thesebastianf** [comment]
@llavorel-somfy is there maybe already an Outlook when this will be added to connexoon Firmware?
Thank you

**Comment by Krisstenswe** [comment]
Another one for local access on Connexoon!

**Comment by ljpaff** [comment]
No updates from Somfy and I still have a half-usable ecosystem. Is there any chance from Somfy to add connexoon in the tahoma system or rollback to previous cloud API?

**Comment by OrbitingOcelot** [comment]
> No updates from Somfy and I still have a half-usable ecosystem. Is there any chance from Somfy to add connexoon in the tahoma system or rollback to previous cloud API?

@ljpaff What problem do you have specifically? For me the cloud API works most of the time. Did you upgrade to Tahoma App and then it stopped working, or do you have another issue?

**Comment by ljpaff** [comment]
> > No updates from Somfy and I still have a half-usable ecosystem. Is there any chance from Somfy to add connexoon in the tahoma system or rollback to previous cloud API?
> 
> @ljpaff What problem do you have specifically? For me the cloud API works most of the time. Did you upgrade to Tahoma App and then it stopped working, or do you have another issue?

Yeah, I upgrade to Tahoma App and now I can't use Cloud API. Anyway there was an email from Somfy that Cloud API will shutdown.

**Comment by cyberhuman** [comment]
Besides, many of us don't want to be dependent on the cloud connection to control our local devices.

**Comment by OrbitingOcelot** [comment]
@ljpaff This is really disturbing news. What were you using to control your blinds before, the Somfy app, Home Assistant, or something else? Previously I was under the impression that the cloud API will continue to work normally after upgrade from Conexxoon to Tahoma App, as described here:
https://community.home-assistant.io/t/overkiz-api-and-somfy-api/61448/1812

@cyberhuman understood and agreed (see 3rd post here). Just want to see if there are any new issues I was not aware about.

**Comment by ljpaff** [comment]
@OrbitingOcelot I think Somfy plans are to migrate all connexoon devices to Tahoma app in order to discontinue de Cloud API because it is an infrastructure (hardware) expense that they probably do not want to assume. So they are openning their closed ecosystem to permit local access to their devices. The problem is that they probably do not want to take into account the connexoon device, which could replace the Tahoma devices in functionality and much cheaper.

**Comment by Stog** [comment]
Consider me another Connexoon owner who would appreciate local API support for this product as it would allow me to have this integrated into my existing home automation ecosystem and make it much more useful. 👍

**Comment by gcatellani** [comment]
+1 My whole Smarthome setup runs locally with the exception of Somfy based products. So with Dev Mode on my Connexoons I‘d finally be fully autonomous.

**Comment by llavorel-somfy** [comment]
Released this week

**Comment by barryhartman** [comment]
> Released this week

That’s fantastics news. Can you elaborate a bit more on the functionality? How do you enable it for example?

**Comment by etique57** [comment]
@barryhartman fantastic news indeed.

To enable the developper mode, go to:
https://www.somfy.fr/ -> My Account -> use your credentials to log-in.

Then click on your connexoon box and right at the bottom you should see the "developper mode activation" button.

Now I still need to figure out how Home-Assistant can leverage it :)

**Comment by TroisSix** [comment]
Great news, let's develop it now for my domoticz ;-)

**Comment by Paul-Vdp** [comment]
Great news, if it weren't for the fact that on acknowledging the developer mode I'm greeted with a 'tahoma.dashboard.devMode.error' and nothing happens.
Can these Somfy IT-ers then NEVER get anything right :-(

**Comment by thesebastianf** [comment]
Upgrade your Firmware First via the app

**Comment by OrbitingOcelot** [comment]
What a pleasant surprise! Thank you! This has considerably restored my view of Somfy as a partner I can trust.

**Comment by Paul-Vdp** [comment]
@thesebastianf Thanks, that worked. Though they might have said so themselves, instead of this cryptic error message

**Comment by JanJaapKo** [comment]
> Great news, let's develop it now for my domoticz ;-)

It is already available: madpatrick/somfy.....

**Comment by cyberhuman** [comment]
I have updated the firmware via the app but still get an error:
![image](https://user-images.githubusercontent.com/979624/213858996-495d3131-1106-447f-b076-5b2e4361d449.png)

**Comment by TroisSix** [comment]
> > Great news, let's develop it now for my domoticz ;-)
> 
> @TroisSix It is already available: [MadPatrick/somfy](https://github.com/MadPatrick/somfy)

Yes, I updated the plugin and it works now on local ^^
Thank you somfy developers to have finally made it possible for our connexoons ;-)

**Comment by lucidph3nx** [comment]
This option doesn't appear to show on the somfy.com.au site serving Australia and New Zealand.
It could just be that they haven't enabled it yet, I worry with the fragmented Somfy ecosystem, this could still be a long way off

**Comment by neugenn** [comment]
Can someone please confirm that 2022.6.4-13 (as reported by TaHoma mobile app) is the firmware version that enables local API on Connexoon ?
Thank you.

**Comment by llavorel-somfy** [comment]
I confirm
