### ISSUE TITLE
How to detect when the developper mode is enabled?

### ISSUE THREAD

**Issue by tetienne** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#90]
To enhance the user experience within Home Assistant (and for other iot hub), it would be nice to have the status of the dev mode returned by the cloud API. This status would have 3 states: 
* `enabled`: the end user has enabled the dev mode on his Tahoma
* `disabled`: the end user has not enabled the dev mode on this Tahoma
* `not supported`: the dev mode is not supported by the box

**Comment by Velocet** [comment]
Why not use mDNS and/or ping the local api?

Bonus: Show a hint about the local api but keep the wording simple: Image a non tech savvy person that doesnt know what a so called „API“ is :)

**Comment by tetienne** [comment]
@llavorel-somfy @vhenriet-sfy Any feedback?

**Comment by llavorel-somfy** [comment]
You can use the `GET /setup/options/developerMode-{{gatewayId}}`.
If the payload is empty '{}', the mode id disabled.

**Comment by tetienne** [comment]
That’s perfect. Many thx.
