### ISSUE TITLE
Documentation should inform readers that developer mode is missing from many TaHoma hubs

### ISSUE THREAD

**Issue by jseyster** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#92]
I bought a new TaHoma Beecon (#1811731C) expecting to be able to control it using this API but only found out after the purchase that developer mode is currently disabled on all North American TaHoma products. I would have preferred to know that before purchasing. All the documentation I've seen about this API gave me an impression that it is a universally supported feature of TaHoma hubs.

The top-level README should include a comprehensive list of TaHoma products indicating whether API access is open for them so that customers can know before buying and so that third-party software providers can let their users know what to expect.

I'd also be interested in a timeline for future Beecon firmware with TaHoma support. The hardware supports it, based on what I've read, and being able to control shades when Internet connections (or the TaHoma cloud service) are unreliable is an important feature that most users will want. There is already another issue filed asking this question that has gone unanswered for a long time. Thanks!

**Comment by jseyster** [comment]
Update: I can't speak definitively about the roadmap, but based on what I've been told, my impression is that there are no plans to add developer mode support to the TaHoma Beecon.

It doesn't look like the unclear documentation will be improved either :(. Best I can do is repeat what I've learned here, so hopefully at least some users will see it and be better informed. *No North American products support this local API.* If you are looking to integrate RTS window coverings with any home automation systems, my advice is to avoid using a TaHoma hub.

**Comment by Velocet** [comment]
Isn't MyLink supposed to provide RTS support?

**Comment by jseyster** [comment]
> Isn't MyLink supposed to provide RTS support?

I think it does, but I don't know much about it. It has some kind of API access via a different API. I'm not sure if its API is accessible without going through a cloud service, which is what I'm primarily looking for.

Thanks for the suggestion! Perhaps somebody who has experience with the MyLink can comment on its capabilities.
