### ISSUE TITLE
Local API not accessible when Somfy servers are down

### ISSUE THREAD

**Issue by rubensworks** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#93]
When the Somfy API goes down (which seems to happen quite frequently), it looks like the local API also becomes inaccessible (bad credentials).
Is this an inherent limitation of the local API, or is this a bug?

**Comment by arikadiusz** [comment]
I only noticed it stopped working today.

**Comment by nickngsr** [comment]
I have to say I don't have this issue, once a token is generated and activated the local API continues to work, I have an offline system that has no issues. Of course generating a token won't work if the cloud services go down but you only ever need to do that once.

**Comment by tomas-kulhanek** [comment]
I have same problem. But i cannot resolve Tahoma box via `gateway-<PIN>.local` at now and i dont know why... :\

**Comment by nickngsr** [comment]
I still don't have any issue connecting and controlling via the TaHoma while it is offline (red led on the bottom, no internet etc).

> I have same problem. But i cannot resolve Tahoma box via `gateway-<PIN>.local` at now and i dont know why... :\

Can you connect using the IP of the device? Could be an issue with mdns on your network.

**Comment by tomas-kulhanek** [comment]
IP address is possible to use it.

If you mean Multicast by mDNS, I have this enabled on my router.

Unfortunately, the Homebridge plugin uses the DNS name for the connection.

What I observed is that the DNS record works for about 10 minutes and then it no longer works according to the ping.
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/7447745/230952085-a408d5d7-ab37-491c-bd6f-2f4bcdd42734.png">

**Comment by bjorn085** [comment]
Some devices have problem with mdns. On my synology for example I'm unable to use mdns address, i have to use IP.
If IP is working, I would advice to go on with IP and don't try too hard to use mdns :)

**Comment by vhenriet-sfy** [comment]
The local api do not require a cloud access a soons as the token has been created.
