### ISSUE TITLE
Problem generating token

### ISSUE THREAD

**Issue by LukeIsBusy** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#95]
Hello guys,

I am using a somfy switch.
I successfully authenticated using: 
curl -X POST https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/login -d "userId=myemail@gmail.com&userPassword=myPassword" -H "Content-Type: application/x-www-form-urlencoded" -c ./cookie

I got a Session ID back:
```
 # Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.
#HttpOnly_ha101-1.overkiz.com	FALSE	/enduser-mobile-web	TRUE	0	JSESSIONID	7C49EBCE8E3F0C3D75A195BB020xxxx
```

but then when generating a token
curl https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxx-xxxx-xxxx/local/tokens/generate -b "JSESSIONID=7C49EBCE8E3F0C3D75A195BB020xxxx” -H "Accept:application/json” 

I just get the response:
{"errorCode":"RESOURCE_ACCESS_DENIED","error":"Not authenticated"}%  

What am I doing wrong? 
Is there something broke on server side?

Thanks in advance! 
Lukas

**Comment by mguellsegarra** [comment]
Same here.

**Comment by markus-ta** [comment]
@mguellsegarra @LukeIsBusy I have the same issue. Did you solve it?

**Comment by mguellsegarra** [comment]
> @mguellsegarra @LukeIsBusy I have the same issue. Did you solve it?

Nope, I ended up using HomeKit local control instead. This API seems unstable.

**Comment by markus-ta** [comment]
> > @mguellsegarra @LukeIsBusy I have the same issue. Did you solve it?
> 
> Nope, I ended up using HomeKit local control instead. This API seems unstable.

Ok, thanks for your response 🥇

**Comment by mguellsegarra** [comment]
> > > @mguellsegarra @LukeIsBusy I have the same issue. Did you solve it?
> > 
> > 
> > Nope, I ended up using HomeKit local control instead. This API seems unstable.
> 
> Ok, thanks for your response 🥇

You're welcome! I don't know your use case, but from my pov, you should check out other alternatives, sadly.

**Comment by bjorn085** [comment]
I don't use cURL but I found some people using --header to pass the cookie instead of -b


curl "https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/1234-5678-9012/local/tokens/generate" --header "Cookie: JSESSIONID=XXXXXXXXX"

Maybe you can try this.

**Comment by j1schmid** [comment]
In my case the `-b` resp. `--cookie` flag works. Given a cookie retrived by
```
MAILADDRESS="name@domain.com"
PASSWORD="mysecret"

curl -X POST --cookie-jar cookie -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" --data-ascii "userId=${MAILADDRESS}&userPassword=${PASSWORD}" https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/login
```
I can list the tokens by
``` 
POD="XXXX-XXXX-XXXX"
curl -X GET --cookie cookie -H "Content-Type: application/json" "https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/${POD}/local/tokens/devmode"
```
and also generate and activate a token.

**Comment by charly83** [comment]
Could you solve the problem? I'm stuck when activating the token. 

I have executed the following:
curl https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/xxxx-xxxx-xxxx/local/tokens -b "JSESSIONID=xxxxxx" -H "Content-Type:application/json" -d "{"label":"mytoken","token":"xxxxxx","scope":"devmode"}"

{"errorCode":"INVALID_API_CALL","error":"Invalid JSON format or type in request body"}
