### ISSUE TITLE
Is it possiple to control Rolling Shutters via php

### ISSUE THREAD

**Issue by Jumbo125** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#97]
Hello
I have the tahoma bx since a short time.
At the moment,  write a script for a local website, to show camera, water infos, electirc sckets and more. It would be nice, if i can cntrll my rolling shutters via webbrowser.
is it possible to control it with php?
Thanks a lot

**Comment by tetienne** [comment]
Well, that’s an API so you can call it using the language you want.

**Comment by Jumbo125** [comment]
He cool.
Do you know where i can find some docs about controll the rolling shutters via ip, php.???
Thank you

**Comment by Tamas-Toth-ebola** [comment]
As an API, there is/are one/more endpoints for it... there is an authentication method... and after it, you can do whatever you want. Basically, the API does not have to care about PHP or any other client-side language, as it just offers an URL to call with the managed parameters.

In your case, you have to know how can you invoke a remote call with the proper parameters from PHP, as you mentioned that language is your choice. Of course, you have to know what and how the API offers, but all further jobs are yours in PHP, in your own way.

For some APIs _(as some FB, some Google etc.)_ there are client-side libraries - in different languages - to handle those API-s, without the knowledge of the raw API functions, but I think Somfy is 'not on that level'.

So check the documentation _(what you already asked for)_, but you have to do everything on your own in PHP, if you know it.

**Comment by Jumbo125** [comment]
okay, i thought there is a simple docu which show what paramters need to be use....
i think thats to difficult for me...
