### ISSUE TITLE
Somfy protect

### ISSUE THREAD

**Issue by cmartinl** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#98]
I want to create a developer account for an application that triggers my alarm when a sensor in my garden is activated. The documentation on https://api.myfox.io/api/ seems clear to me, but I can't create my developer account on the url https://api.myfox.io/api/registration which is showing an error.

Can you tell me how to get an API key?

Thank you,

Charles Martin-Laval"

**Comment by llavorel-somfy** [comment]
Hi @cmartinl 
The Somfy Protect API is not part of the TaHoma Developer Mode. Could you please try to reach out the support from the somfy assistance forum ?
